/*=============================================================================================*/
/* Project name: test2 */
/* Project version: aaa */
/*---------------------------------------------------------------------------------------------*/
/* Generated by Aqualis (algorithm and equation analyzer for lightwave simulation) */
/* Aqualis version: aaa */
/* Generated date: 2023/11/25 6:57:55 */
/*=============================================================================================*/
#include <stdio.h>
#include <stdlib.h>
#include <complex.h>
#include <math.h>
#undef I
#define uj _Complex_I
int ic001;
int ic002;
int i001;
int i002;
double d001;
double d002;
double d003;
double complex z001;
double complex z002;
double *d1001;
int d1001_size[1]={-1};
double *d1002;
int d1002_size[1]={-1};
double *d1003;
int d1003_size[1]={-1};
double *d2001;
int d2001_size[2]={-1,-1};
double *d2002;
int d2002_size[2]={-1,-1};
double *d2003;
int d2003_size[2]={-1,-1};
int main()
{
  /* %%%test1%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% */
    /* 001 */
    i002 = 1;
    /* 002 */
    i001 = i002+1;
    /* 003 */
    i001 = i001+i002;
    /* 004 */
    i001 = (i001+i002)*(i001+i002);
    /* 005 */
    d001 = 1;
    /* 006 */
    d002 = d001/d002/d002;
    /* 007 */
    i001 = i001-i002;
    /* 008 */
    d001 = (double)(i001)/(double)(i002);
    /* 009 */
    i001 = i001/i002;
    /* 010 */
    printf("%8d\n",i002);
    printf("%8d\n",i002);
    printf("%8d\n",i002+1);
    /* 011 */
    i002 = -1;
    /* 012 */
    i001 = 1-i002;
    /* 013 */
    i001 = i002-i001;
    /* 014 */
    i001 = -(i001+i002)*(i001+i002);
    /* 015 */
    d001 = (double)(-(i001+i002))/((double)(i001)+(double)(i002));
    /* 016 */
    d002 = -d001/d002/d002;
    /* 017 */
    i001 = -(i001+i002);
    /* 018 */
    d001 = (double)(-i001)/(double)(i002);
    /* 019 */
    i001 = -i001/i002;
    /* 020 */
    d001 = 2.0E0*(double)(i001);
    /* 021 */
    i001 = 2*i001;
    /* 022 */
    d002 = sin(-(d001+d002)/d001);
    d002 = cos(d001);
    d002 = tan(d001);
    d002 = exp(d001);
    d002 = log(d001);
    d002 = log10(d001);
    d002 = sqrt(d001);
    d002 = asin(d001);
    d002 = acos(d001);
    d002 = atan(d001);
    d002 = atan2(d001,d002);
    d002 = floor(d001);
    d002 = ceil(d001);
  /* %%%end test1%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% */
    
  /* %%%test2%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% */
    d1001_size[0] = 10;
    d1001=(double *)malloc(sizeof(double)*d1001_size[0]);
    d1002_size[0] = 10;
    d1002=(double *)malloc(sizeof(double)*d1002_size[0]);
    d1003_size[0] = 10;
    d1003=(double *)malloc(sizeof(double)*d1003_size[0]);
    /* 021 */
    for(ic001=1; ic001<=d1003_size[0]; ic001++)
    {
      d1003[ic001-1] = d1001[ic001-1]+d1002[ic001-1];
    }
    /* 022 */
    for(ic001=1; ic001<=3; ic001++)
    {
      d1003[ic001-1] = d1001[ic001+2]+d1002[ic001+2];
    }
    /* 023 */
    for(ic001=1; ic001<=d1003_size[0]; ic001++)
    {
      d1003[ic001-1] = d1001[ic001-1]*(d1001[ic001-1]+d1002[ic001-1]);
    }
    d1003_size[0] = -1;
    free(d1003);
    d2001_size[0] = 10;
    d2001_size[1] = 5;
    d2001=(double *)malloc(sizeof(double)*d2001_size[0]*d2001_size[1]);
    d2002_size[0] = 10;
    d2002_size[1] = 5;
    d2002=(double *)malloc(sizeof(double)*d2002_size[0]*d2002_size[1]);
    d2003_size[0] = 10;
    d2003_size[1] = 5;
    d2003=(double *)malloc(sizeof(double)*d2003_size[0]*d2003_size[1]);
    /* 024 */
    for(ic001=1; ic001<=d2003_size[0]; ic001++)
    {
      for(ic002=1; ic002<=d2003_size[1]; ic002++)
      {
        d2003[(ic002-1)*d2003_size[0]+ic001-1] = d2001[(ic002-1)*d2001_size[0]+ic001-1]+d2002[(ic002-1)*d2002_size[0]+ic001-1];
      }
    }
    /* 025 */
    for(ic001=1; ic001<=3; ic001++)
    {
      d2003[2*d2003_size[0]+ic001-1] = d2001[2*d2001_size[0]+ic001+2]+d2002[2*d2002_size[0]+ic001+2];
    }
    /* 026 */
    for(ic001=1; ic001<=d2003_size[0]; ic001++)
    {
      for(ic002=1; ic002<=d2003_size[1]; ic002++)
      {
        d2003[(ic002-1)*d2003_size[0]+ic001-1] = d2001[(ic002-1)*d2001_size[0]+ic001-1]*(d2001[(ic002-1)*d2001_size[0]+ic001-1]+d2002[(ic002-1)*d2002_size[0]+ic001-1]);
      }
    }
    d2003_size[0] = -1;
    free(d2003);
    /* 027 */
    i001 = 1;
    /* 028 */
    i001 = 1;
    i002 = 1;
    i002 = 8*i001;
    /* aaa */
    d001 = 2.0E0*(double)(i001);
    /* bbb */
    i002 = 2*i001;
    /* ccc */
    d2002_size[0] = -1;
    free(d2002);
    d2001_size[0] = -1;
    free(d2001);
    d1002_size[0] = -1;
    free(d1002);
    d1001_size[0] = -1;
    free(d1001);
  /* %%%end test2%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% */
    
  /* %%%test3%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% */
    /* 001 */
    i001 = 2*i001;
    /* 002 */
    i001 = 0;
    /* 003 */
    d001 = 1;
    /* 004 */
    i001 = 1;
    /* 005 */
    d001 = 2*(i001+d001);
    /* 006 */
    d001 = 4*i001;
    /* 007 */
    d001 = 0;
    /* 008 */
    d001 = 0;
    /* 009 */
    d001 = 1;
    /* 010 */
    d001 = 1;
    /* 011 */
    d001 = 1;
  /* %%%end test3%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% */
    
  /* %%%test4%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% */
    /* 001 */
    i001 = -2;
    d001 = sin((double)(i001));
    printf("%27.17e\n",d001);
    d001 = cos((double)(i001));
    printf("%27.17e\n",d001);
    d001 = tan((double)(i001));
    printf("%27.17e\n",d001);
    d001 = exp((double)(i001));
    printf("%27.17e\n",d001);
    d001 = log((double)(i001));
    printf("%27.17e\n",d001);
    d001 = log10((double)(i001));
    printf("%27.17e\n",d001);
    d001 = sqrt((double)(i001));
    printf("%27.17e\n",d001);
    d001 = asin((double)(i001));
    printf("%27.17e\n",d001);
    d001 = acos((double)(i001));
    printf("%27.17e\n",d001);
    d001 = atan((double)(i001));
    printf("%27.17e\n",d001);
    d001 = atan2((double)(i001),d001);
    printf("%27.17e\n",d001);
    /* 002 */
    d001 = 1.2E0;
    d003 = sin(d001);
    printf("%27.17e\n",d003);
    d003 = cos(d001);
    printf("%27.17e\n",d003);
    d003 = tan(d001);
    printf("%27.17e\n",d003);
    d003 = exp(d001);
    printf("%27.17e\n",d003);
    d003 = log(d001);
    printf("%27.17e\n",d003);
    d003 = log10(d001);
    printf("%27.17e\n",d003);
    d003 = sqrt(d001);
    printf("%27.17e\n",d003);
    d003 = asin(d001);
    printf("%27.17e\n",d003);
    d003 = acos(d001);
    printf("%27.17e\n",d003);
    d003 = atan(d001);
    printf("%27.17e\n",d003);
    d003 = atan2(d001,d002);
    printf("%27.17e\n",d003);
    d003 = floor(d001);
    printf("%27.17e\n",d003);
    d003 = ceil(d001);
    printf("%27.17e\n",d003);
    /* 003 */
    z001 = 1.0E0-uj*2.0E0;
    z002 = csin(z001);
    printf("%27.17e%27.17e\n",creal(z002),cimag(z002));
    z002 = ccos(z001);
    printf("%27.17e%27.17e\n",creal(z002),cimag(z002));
    z002 = ctan(z001);
    printf("%27.17e%27.17e\n",creal(z002),cimag(z002));
    z002 = cexp(z001);
    printf("%27.17e%27.17e\n",creal(z002),cimag(z002));
    z002 = log(z001);
    printf("%27.17e%27.17e\n",creal(z002),cimag(z002));
    z002 = sqrt(z001);
    printf("%27.17e%27.17e\n",creal(z002),cimag(z002));
    z002 = casin(z001);
    printf("%27.17e%27.17e\n",creal(z002),cimag(z002));
    z002 = cacos(z001);
    printf("%27.17e%27.17e\n",creal(z002),cimag(z002));
    z002 = catan(z001);
    printf("%27.17e%27.17e\n",creal(z002),cimag(z002));
  /* %%%end test4%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% */
    
  return 0;
}
