!=============================================================================================
! Project name: test3_2
! Project version: aaa
!---------------------------------------------------------------------------------------------
! Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)
! Aqualis version: aaa
! Generated date: 2025/08/26 1:58:54
!=============================================================================================
program test3_2
implicit none
type testClass1
  integer :: n1
end type testClass1
type testClass2
  type(testClass1),allocatable :: t2(:)
  integer :: t2_size(1:1)
end type testClass2
type(testClass2),allocatable :: q(:)
integer :: q_size(1:1)=(/ -1 /)
q_size(1) = 5
allocate(q(1:q_size(1)))
q(2)%t2_size(1) = 2
allocate(q(2)%t2(1:q(2)%t2_size(1)))
q(2)%t2(3)%n1 = 2000
print *, q(2)%t2(3)%n1

contains

end program test3_2
