/*=============================================================================================*/
/* Project name: test7 */
/* Project version: aaa */
/*---------------------------------------------------------------------------------------------*/
/* Generated by Aqualis (algorithm and equation analyzer for lightwave simulation) */
/* Aqualis version: aaa */
/* Generated date: 2023/11/28 12:25:28 */
/*=============================================================================================*/
#include <stdio.h>
#include <stdlib.h>
#include <complex.h>
#include <math.h>
#undef I
#define uj _Complex_I
int ic001;
int ic002;
int i0001;
int i0002;
double d0001;
double d0002;
double d0003;
double d0004;
double d0005;
double d0006;
double d0007;
double d0008;
double d0009;
double d0010;
double d0011;
double *d10001;
int d10001_size[1]={-1};
int main()
{
  d0001 = -10;
  /* ===014========================================================================= */
    d10001_size[0] = 10;
    d10001=(double *)malloc(sizeof(double)*d10001_size[0]);
    for(ic0001=1; ic0001<=d10001_size[0]; ic0001++)
    {
      d10001[ic0001-1] = ic0001;
    }
    for(ic0001=1; ic0001<=d10001_size[0]; ic0001++)
    {
      /* 代数微分 */
      d0006 = 0;
      for(ic0002=1; ic0002<=20; ic0002++)
      {
        if(ic0002 == ic0001)
        {
          i0001 = 1;
        }
        else
        {
          i0001 = 0;
        }
        d0006 = d0006+ic0002*ic0002*i0001;
      }
      d0007 = 0;
      for(ic0002=1; ic0002<=10; ic0002++)
      {
        d0007 = d0007+ic0002*d10001[ic0002-1];
      }
      d0008 = 0;
      for(ic0002=1; ic0002<=20; ic0002++)
      {
        d0008 = d0008+ic0002*ic0002*d10001[ic0002-1];
      }
      d0009 = 0;
      for(ic0002=1; ic0002<=10; ic0002++)
      {
        d0009 = d0009+ic0002*d10001[ic0002-1];
      }
      d0010 = 0;
      for(ic0002=1; ic0002<=10; ic0002++)
      {
        if(ic0002 == ic0001)
        {
          i0002 = 1;
        }
        else
        {
          i0002 = 0;
        }
        d0010 = d0010+ic0002*i0002;
      }
      d0011 = 0;
      for(ic0002=1; ic0002<=10; ic0002++)
      {
        d0011 = d0011+ic0002*d10001[ic0002-1];
      }
      d0004 = d0006/sqrt(d0007)-d0008/pow(sqrt(d0009),2)*5.0E-1*d0010/sqrt(d0011);
    }
    d10001_size[0] = -1;
    free(d10001);
  /* ===end 014===================================================================== */
    
  return 0;
}
