/*=============================================================================================*/
/* Project name: test6tw */
/* Project version: aaa */
/*---------------------------------------------------------------------------------------------*/
/* Generated by Aqualis (algorithm and equation analyzer for lightwave simulation) */
/* Aqualis version: aaa */
/* Generated date: 2023/11/25 7:07:26 */
/*=============================================================================================*/
#include <stdio.h>
#include <stdlib.h>
#include <complex.h>
#include <math.h>
#undef I
#define uj _Complex_I
char byte_tmp;
char t001[100];
FILE* f001;
int i001;
int i002;
double d001;
double complex z001;
int main()
{
  i001 = 1;
  i002 = 2;
  d001 = 1.234E0;
  z001 = 5.6E0+uj*7.8E0;
  sprintf(t001,"testA%08d_%08d.dat",i001,i002);
  f001 = fopen(t001,"w");
  fprintf(f001,"%8d\t%8d\t%8d\n",i001,i001+1,i001+2);
  fprintf(f001,"%8d\t%8d\t%8d\n",i001+3,i001+4,i001+5);
  fprintf(f001,"%27.17e\t%27.17e\t%27.17e\n",d001,creal(z001),cimag(z001));
  fprintf(f001,"%27.17e\t%27.17e\t%27.17e\n",sin(d001),creal(cexp(z001)),cimag(cexp(z001)));
  fprintf(f001,"%27.17e\n",d001+cos(d001));
  fprintf(f001,"%27.17e\t%27.17e\n",fabs(z001),pow(fabs(z001),2));
  fclose(f001);
  return 0;
}
