!=============================================================================================
! Project name: test0
! Project version: bbb
!---------------------------------------------------------------------------------------------
! Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)
! Aqualis version: aaa
! Generated date: 2023/10/21 16:14:10
!=============================================================================================
program test0
implicit none
double precision :: pi=3.14159265358979d0
double precision :: y
double precision :: x
integer :: ic001
integer :: ic002
double precision :: d001
double precision,allocatable :: d1001(:)
integer :: d1001_size(1:1)=(/ -1 /)
complex(kind(0d0)),allocatable :: z2001(:,:)
integer :: z2001_size(1:2)=(/ -1,-1 /)
x = pi
y = 1
d1001_size(1) = 10
allocate(d1001(1:d1001_size(1)))
z2001_size(1) = 10
z2001_size(2) = 20
allocate(z2001(1:z2001_size(1),1:z2001_size(2)))
d001 = sin(x)
do ic001=1,d1001_size(1)
  d1001(ic001) = d1001(ic001)/dble(d1001_size(1))
end do
do ic001=1,z2001_size(1)
  do ic002=1,z2001_size(2)
    z2001(ic001,ic002) = z2001(ic001,ic002)/(dble(z2001_size(1))*dble(z2001_size(2)))
    z2001(ic001,ic002) = (z2001(ic001,ic002)+x*d001/y)/(dble(z2001_size(1))*dble(z2001_size(2)))
  end do
end do
z2001_size(1) = -1
deallocate(z2001)
d1001_size(1) = -1
deallocate(d1001)

contains

end program test0
