!=============================================================================================
! Project name: test6tw
! Project version: aaa
!---------------------------------------------------------------------------------------------
! Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)
! Aqualis version: aaa
! Generated date: 2023/11/21 23:37:41
!=============================================================================================
program test6tw
implicit none
double precision :: d001
d001 = 10
print *, 1

contains

end program test6tw
