#=============================================================================================
# Project name: test3_2 
# Project version: aaa */
#---------------------------------------------------------------------------------------------
# Generated by Aqualis (algorithm and equation analyzer for lightwave simulation) #
# Aqualis version: aaa #
# Generated date: 2025/08/26 1:58:54 #
#=============================================================================================
import numpy
import math
import cmath
import copy
import struct
import re
from scipy.linalg import solve, svd, eig, lu
from scipy.special import jv, yn
import sys
class testClass1:
  n1 = 0
class testClass2:
  t2 = numpy.array([], dtype=object)
  t2_size = numpy.zeros(1,dtype=int)
q = numpy.array([], dtype=object)
q_size = numpy.array([-1])
q_size[0] = 5
q = numpy.array([testClass2() for _ in range(int(q_size[0]))], dtype=object)
q[1].t2_size[0] = 2
q[1].t2 = numpy.array([testClass1() for _ in range(int(q[1].t2_size[0]))], dtype=object)
q[1].t2[2].n1 = 2000
print("%8d" %(q[1].t2[2].n1))
