!=============================================================================================
! Project name: test7
! Project version: aaa
!---------------------------------------------------------------------------------------------
! Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)
! Aqualis version: aaa
! Generated date: 2023/11/28 12:25:28
!=============================================================================================
program test7
implicit none
integer :: ic0001
integer :: ic0002
integer :: i0001
integer :: i0002
double precision :: d0001
double precision :: d0002
double precision :: d0003
double precision :: d0004
double precision :: d0005
double precision :: d0006
double precision :: d0007
double precision :: d0008
double precision :: d0009
double precision :: d0010
double precision :: d0011
double precision,allocatable :: d10001(:)
integer :: d10001_size(1:1)=(/ -1 /)
d0001 = -10
!===014=========================================================================
  d10001_size(1) = 10
  allocate(d10001(1:d10001_size(1)))
  do ic0001=1,d10001_size(1)
    d10001(ic0001) = ic0001
  end do
  do ic0001=1,d10001_size(1)
    !代数微分
    d0006 = 0
    do ic0002=1,20
      if(ic0002 == ic0001) then
        i0001 = 1
      else
        i0001 = 0
      end if
      d0006 = d0006+ic0002*ic0002*i0001
    end do
    d0007 = 0
    do ic0002=1,10
      d0007 = d0007+ic0002*d10001(ic0002)
    end do
    d0008 = 0
    do ic0002=1,20
      d0008 = d0008+ic0002*ic0002*d10001(ic0002)
    end do
    d0009 = 0
    do ic0002=1,10
      d0009 = d0009+ic0002*d10001(ic0002)
    end do
    d0010 = 0
    do ic0002=1,10
      if(ic0002 == ic0001) then
        i0002 = 1
      else
        i0002 = 0
      end if
      d0010 = d0010+ic0002*i0002
    end do
    d0011 = 0
    do ic0002=1,10
      d0011 = d0011+ic0002*d10001(ic0002)
    end do
    d0004 = d0006/sqrt(d0007)-d0008/sqrt(d0009)**(2)*5.0d-1*d0010/sqrt(d0011)
  end do
  d10001_size(1) = -1
  deallocate(d10001)
!===end 014=====================================================================

contains

end program test7
