!=============================================================================================
! Project name: test7
! Project version: aaa
!---------------------------------------------------------------------------------------------
! Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)
! Aqualis version: aaa
! Generated date: 2023/11/28 14:52:29
!=============================================================================================
program test7
implicit none
double precision :: tmp2
double precision :: tmp1
integer :: ic0001
integer :: ic0002
integer :: i0001
integer :: i0002
integer :: i0003
integer :: i0004
double precision :: d0001
double precision :: d0002
double precision :: d0003
double precision :: d0004
double precision :: d0005
double precision :: d0006
double precision :: d0007
double precision :: d0008
double precision :: d0009
double precision :: d0010
double precision :: d0011
double precision :: d0012
double precision :: d0013
double precision :: d0014
double precision :: d0015
double precision :: d0016
double precision :: d0017
double precision :: d0018
double precision :: d0019
double precision :: d0020
double precision :: d0021
double precision :: d0022
double precision :: d0023
double precision,allocatable :: d10001(:)
integer :: d10001_size(1:1)=(/ -1 /)
d0001 = -10
!===014a========================================================================
  d10001_size(1) = 10
  allocate(d10001(1:d10001_size(1)))
  do ic0001=1,d10001_size(1)
    d10001(ic0001) = ic0001
  end do
  do ic0001=1,d10001_size(1)
    !代数微分
    d0006 = 0
    do ic0002=1,20
      if(ic0002 == ic0001) then
        i0001 = 1
      else
        i0001 = 0
      end if
      d0006 = d0006+ic0002*ic0002*i0001
    end do
    d0007 = 0
    do ic0002=1,10
      d0007 = d0007+ic0002*d10001(ic0002)
    end do
    d0008 = 0
    do ic0002=1,20
      d0008 = d0008+ic0002*ic0002*d10001(ic0002)
    end do
    d0009 = 0
    do ic0002=1,10
      d0009 = d0009+ic0002*d10001(ic0002)
    end do
    d0010 = 0
    do ic0002=1,10
      if(ic0002 == ic0001) then
        i0002 = 1
      else
        i0002 = 0
      end if
      d0010 = d0010+ic0002*i0002
    end do
    d0011 = 0
    do ic0002=1,10
      d0011 = d0011+ic0002*d10001(ic0002)
    end do
    d0004 = d0006/sqrt(d0007)-d0008/sqrt(d0009)**(2)*5.0d-1*d0010/sqrt(d0011)
    !数値微分
    d0012 = 0
    do ic0002=1,20
      d0012 = d0012+ic0002*ic0002*d10001(ic0002)
    end do
    d0013 = 0
    do ic0002=1,10
      d0013 = d0013+ic0002*d10001(ic0002)
    end do
    d0002 = d0012/sqrt(d0013)
    d10001(ic0001) = d10001(ic0001)+1.0d-7
    d0014 = 0
    do ic0002=1,20
      d0014 = d0014+ic0002*ic0002*d10001(ic0002)
    end do
    d0015 = 0
    do ic0002=1,10
      d0015 = d0015+ic0002*d10001(ic0002)
    end do
    d0003 = d0014/sqrt(d0015)
    d10001(ic0001) = d10001(ic0001)-1.0d-7
    print *, ic0001,d0004,(d0003-d0002)/1.0d-7
  end do
  d10001_size(1) = -1
  deallocate(d10001)
!===end 014a====================================================================
!===014b========================================================================
  d10001_size(1) = 10
  allocate(d10001(1:d10001_size(1)))
  do ic0001=1,d10001_size(1)
    d10001(ic0001) = ic0001
  end do
  d0016 = 0
  do ic0001=1,20
    d0016 = d0016+ic0001*ic0001*d10001(ic0001)
  end do
  tmp1 = d0016
  d0017 = 0
  do ic0001=1,10
    d0017 = d0017+ic0001*d10001(ic0001)
  end do
  tmp2 = d0017
  do ic0001=1,d10001_size(1)
    !代数微分
    d0018 = 0
    do ic0002=1,20
      if(ic0002 == ic0001) then
        i0003 = 1
      else
        i0003 = 0
      end if
      d0018 = d0018+ic0002*ic0002*i0003
    end do
    d0019 = 0
    do ic0002=1,10
      if(ic0002 == ic0001) then
        i0004 = 1
      else
        i0004 = 0
      end if
      d0019 = d0019+ic0002*i0004
    end do
    d0004 = d0018/sqrt(tmp2)-tmp1/sqrt(tmp2)**(2)*5.0d-1*d0019/sqrt(tmp2)
    !数値微分
    d0002 = tmp1/sqrt(tmp2)
    d10001(ic0001) = d10001(ic0001)+1.0d-7
    d0020 = 0
    do ic0002=1,20
      d0020 = d0020+ic0002*ic0002*d10001(ic0002)
    end do
    tmp1 = d0020
    d0021 = 0
    do ic0002=1,10
      d0021 = d0021+ic0002*d10001(ic0002)
    end do
    tmp2 = d0021
    d0003 = tmp1/sqrt(tmp2)
    d10001(ic0001) = d10001(ic0001)-1.0d-7
    d0022 = 0
    do ic0002=1,20
      d0022 = d0022+ic0002*ic0002*d10001(ic0002)
    end do
    tmp1 = d0022
    d0023 = 0
    do ic0002=1,10
      d0023 = d0023+ic0002*d10001(ic0002)
    end do
    tmp2 = d0023
    print *, ic0001,d0004,(d0003-d0002)/1.0d-7
  end do
  d10001_size(1) = -1
  deallocate(d10001)
!===end 014b====================================================================

contains

end program test7
