!=============================================================================================
! Project name: test6bw
! Project version: aaa
!---------------------------------------------------------------------------------------------
! Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)
! Aqualis version: aaa
! Generated date: 2023/11/25 7:07:26
!=============================================================================================
program test6bw
implicit none
integer(1) :: byte_tmp
character(100) :: t001
integer :: f001=11
complex(kind(0d0)) :: uj=(0d0,1d0)
integer :: ic001
integer :: i001
integer :: i002
double precision :: d001
complex(kind(0d0)) :: z001
i001 = 1
i002 = 2
d001 = 1.234d0
z001 = 5.6d0+uj*7.8d0
write(t001,"(A,I8,A,I8,A)") "testA",i001,"_",i002,".bin"
do ic001 = 1, len_trim(t001)
  if ( t001( ic001:ic001 ).EQ." " ) t001( ic001:ic001 ) = "0"
end do
open(f001, file=trim(t001), access='stream', form='unformatted')
write(f001) i001
write(f001) i001+1
write(f001) i001+2
write(f001) i001+3
write(f001) i001+4
write(f001) i001+5
write(f001) d001
write(f001) real(z001)
write(f001) aimag(z001)
write(f001) sin(d001)
write(f001) real(exp(z001))
write(f001) aimag(exp(z001))
write(f001) d001+cos(d001)
write(f001) abs(z001)
write(f001) abs(z001)**2
close(f001)

contains

end program test6bw
