!=============================================================================================
! Project name: test6tr
! Project version: aaa
!---------------------------------------------------------------------------------------------
! Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)
! Aqualis version: aaa
! Generated date: 2023/10/17 23:15:13
!=============================================================================================
program test6tr
implicit none
integer(1) :: byte_tmp
character(100) :: t001
integer :: f001=11
complex(kind(0d0)) :: uj=(0d0,1d0)
integer :: ic001
integer :: i001
integer :: i002
integer :: i003
integer :: i004
integer :: i005
integer :: i006
integer :: i007
double precision :: d001
double precision :: d002
double precision :: d003
complex(kind(0d0)) :: z001
complex(kind(0d0)) :: z002
integer,allocatable :: i1001(:)
integer :: i1001_size(1:1)=(/ -1 /)
double precision,allocatable :: d1001(:)
integer :: d1001_size(1:1)=(/ -1 /)
i001 = 1
i002 = 2
d001 = 1.234d0
z001 = 5.6d0+uj*7.8d0
write(t001,"(A,I8,A,I8,A)") "testA",i001,"_",i002,".dat"
do ic001 = 1, len_trim(t001)
  if ( t001( ic001:ic001 ).EQ." " ) t001( ic001:ic001 ) = "0"
end do
open(f001, file=trim(t001))
i1001_size(1) = 2
allocate(i1001(1:i1001_size(1)))
read(f001,"(I8,A1,I8,A1,I8)",iostat=i003) i004,i1001(1),i005,i1001(2),i006
i1001_size(1) = -1
deallocate(i1001)
print *, i004,i001
print *, i005,i001+1
print *, i006,i001+2
i1001_size(1) = 2
allocate(i1001(1:i1001_size(1)))
read(f001,"(I8,A1,I8,A1,I8)",iostat=i003) i004,i1001(1),i005,i1001(2),i006
i1001_size(1) = -1
deallocate(i1001)
print *, i004,i001+3
print *, i005,i001+4
print *, i006,i001+5
d1001_size(1) = 2
allocate(d1001(1:d1001_size(1)))
i1001_size(1) = 1
allocate(i1001(1:i1001_size(1)))
read(f001,"(E27.17e3,A1,E27.17e3,A1,E27.17e3)",iostat=i003) d002,i1001(1),d1001(1),i1001(2),d1001(2)
z002 = d1001(1)+uj*d1001(2)
i1001_size(1) = -1
deallocate(i1001)
d1001_size(1) = -1
deallocate(d1001)
print *, d001,d002
print *, real(z001),aimag(z001),real(z002),aimag(z002)
d1001_size(1) = 2
allocate(d1001(1:d1001_size(1)))
i1001_size(1) = 1
allocate(i1001(1:i1001_size(1)))
read(f001,"(E27.17e3,A1,E27.17e3,A1,E27.17e3)",iostat=i003) d002,i1001(1),d1001(1),i1001(2),d1001(2)
z002 = d1001(1)+uj*d1001(2)
i1001_size(1) = -1
deallocate(i1001)
d1001_size(1) = -1
deallocate(d1001)
print *, sin(d001),d002
print *, real(exp(z001)),aimag(exp(z001)),real(z002),aimag(z002)
i1001_size(1) = 0
allocate(i1001(1:i1001_size(1)))
read(f001,"(E27.17e3)",iostat=i003) d002
i1001_size(1) = -1
deallocate(i1001)
print *, d001+cos(d001),d002
i1001_size(1) = 1
allocate(i1001(1:i1001_size(1)))
read(f001,"(E27.17e3,A1,E27.17e3)",iostat=i003) d002,i1001(1),d003
i1001_size(1) = -1
deallocate(i1001)
print *, abs(z001),d002
print *, abs(z001)**2,d003
close(f001)

contains

end program test6tr
