!=============================================================================================
! Project name: test5
! Project version: aaa
!---------------------------------------------------------------------------------------------
! Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)
! Aqualis version: aaa
! Generated date: 2023/10/16 13:33:06
!=============================================================================================
program test5
implicit none
integer :: i001
double precision :: d001
i001 = 1
d001 = 1
d001 = i001
i001 = d001
print *, i001
print *, d001

contains

end program test5
