/*=============================================================================================*/
/* Project name: test6tw */
/* Project version: aaa */
/*---------------------------------------------------------------------------------------------*/
/* Generated by Aqualis (algorithm and equation analyzer for lightwave simulation) */
/* Aqualis version: aaa */
/* Generated date: 2023/11/21 23:37:41 */
/*=============================================================================================*/
#include <stdio.h>
#include <stdlib.h>
#include <complex.h>
#include <math.h>
#undef I
#define uj _Complex_I
double d001;
int main()
{
  d001 = 10;
  printf("%8d\n",1);
  return 0;
}
