/*=============================================================================================*/
/* Project name: test5 */
/* Project version: aaa */
/*---------------------------------------------------------------------------------------------*/
/* Generated by Aqualis (algorithm and equation analyzer for lightwave simulation) */
/* Aqualis version: aaa */
/* Generated date: 2023/11/25 7:06:59 */
/*=============================================================================================*/
#include <stdio.h>
#include <stdlib.h>
#include <complex.h>
#include <math.h>
#undef I
#define uj _Complex_I
double pi=3.14159265358979;
double a;
int i001;
double d001;
int main()
{
  a = pi;
  a = 1;
  i001 = 1;
  d001 = 1.0E0;
  d001 = i001;
  i001 = d001;
  printf("%8d\n",i001);
  printf("%27.17e\n",d001);
  return 0;
}
