!=============================================================================================
! Project name: test6br
! Project version: aaa
!---------------------------------------------------------------------------------------------
! Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)
! Aqualis version: aaa
! Generated date: 2023/10/17 23:15:13
!=============================================================================================
program test6br
implicit none
integer(1) :: byte_tmp
character(100) :: t001
integer :: f001=11
complex(kind(0d0)) :: uj=(0d0,1d0)
integer :: ic001
integer :: i001
integer :: i002
integer :: i003
integer :: i004
integer :: i005
integer :: i006
integer :: i007
double precision :: d001
double precision :: d002
double precision :: d003
double precision :: d004
double precision :: d005
complex(kind(0d0)) :: z001
complex(kind(0d0)) :: z002
i001 = 1
i002 = 2
d001 = 1.234d0
z001 = 5.6d0+uj*7.8d0
write(t001,"(A,I8,A,I8,A)") "testA",i001,"_",i002,".bin"
do ic001 = 1, len_trim(t001)
  if ( t001( ic001:ic001 ).EQ." " ) t001( ic001:ic001 ) = "0"
end do
open(f001, file=trim(t001), access='stream', form='unformatted')
read(f001,iostat=i003) i004
read(f001,iostat=i003) i005
read(f001,iostat=i003) i006
print *, i004,i001
print *, i005,i001+1
print *, i006,i001+2
read(f001,iostat=i003) i004
read(f001,iostat=i003) i005
read(f001,iostat=i003) i006
print *, i004,i001+3
print *, i005,i001+4
print *, i006,i001+5
read(f001,iostat=i003) d002
read(f001,iostat=i003) d004
read(f001,iostat=i003) d005
z002 = d004+uj*d005
print *, d001,d002
print *, real(z001),aimag(z001),real(z002),aimag(z002)
read(f001,iostat=i003) d002
read(f001,iostat=i003) d004
read(f001,iostat=i003) d005
z002 = d004+uj*d005
print *, sin(d001),d002
print *, real(exp(z001)),aimag(exp(z001)),real(z002),aimag(z002)
read(f001,iostat=i003) d002
print *, d001+cos(d001),d002
read(f001,iostat=i003) d002
read(f001,iostat=i003) d003
print *, abs(z001),d002
print *, abs(z001)**2,d003
close(f001)

contains

end program test6br
