!=============================================================================================
! Project name: test5
! Project version: aaa
!---------------------------------------------------------------------------------------------
! Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)
! Aqualis version: aaa
! Generated date: 2023/10/17 23:14:50
!=============================================================================================
program test5
implicit none
double precision :: pi=3.14159265358979d0
double precision :: a
integer :: i001
double precision :: d001
a = pi
a = 1
i001 = 1
d001 = 1.0d0
d001 = i001
i001 = d001
print *, i001
print *, d001

contains

end program test5
