/*=============================================================================================*/
/* Project name: test3_2 */
/* Project version: aaa */
/*---------------------------------------------------------------------------------------------*/
/* Generated by Aqualis (algorithm and equation analyzer for lightwave simulation) */
/* Aqualis version: aaa */
/* Generated date: 2025/08/26 1:58:54 */
/*=============================================================================================*/
#include <stdio.h>
#include <stdlib.h>
#include <complex.h>
#include <math.h>
#undef I
#define uj _Complex_I
typedef struct _testClass1
{
  int n1;
} testClass1;
typedef struct _testClass2
{
  testClass1 *t2;
  int t2_size[1];
} testClass2;
testClass2 *q;
int q_size[1]={ -1 };
int main()
{
  q_size[0] = 5;
  q=(testClass2 *)malloc(sizeof(testClass2)*q_size[0]);
  q[1].t2_size[0] = 2;
  q[1].t2=(testClass1 *)malloc(sizeof(testClass1)*q[1].t2_size[0]);
  q[1].t2[2].n1 = 2000;
  printf("%8d\n",q[1].t2[2].n1);
  return 0;
}
