//
// Copyright (c) 2026 Jun-ichiro Sugisaka
//
// This software is released under the MIT License.
// http://opensource.org/licenses/mit-license.php
//
namespace Aqualis

    module internal ShellCommand =
        let private quoteArgument (value:string) =
            if isNull value then
                nullArg (nameof value)
            if value.IndexOf '\u0000' >= 0 then
                invalidArg (nameof value) "A shell argument cannot contain NUL."

            let isSafe character =
                System.Char.IsLetterOrDigit character ||
                "_-./:=+@%,".Contains character

            if value <> "" && value |> Seq.forall isSafe then
                value
            else
                "'" + value.Replace("'", "'\"'\"'") + "'"

        let buildCommand executable arguments =
            executable::arguments
            |> List.filter (System.String.IsNullOrWhiteSpace >> not)
            |> List.map quoteArgument
            |> String.concat " "

        let buildCompileCommand
            compiler
            fixedArguments
            sources
            mainSource
            options
            output =
            buildCommand compiler [
                yield! fixedArguments
                yield! sources
                yield mainSource
                yield! options
                yield "-o"
                yield output
            ]

    open System
    open System.IO

    [<AutoOpen>]
    module Aqualis_main =

        ///<summary>コンパイル</summary>
        let Compile langgList dir projectname (codever:string) code =
            for lang in langgList do
                match lang with
                |Fortran ->
                    makeProgramWithContext [dir,projectname,Fortran] <| fun context ->
                        //メインコード生成
                        let environment = Aqualis(Some context)
                        code environment
                        context.CurrentProgram.close()
                        //ソースファイル出力
                        use writer = new codeWriter(dir + "\\" + projectname + ".f90", 2, Fortran)
                        writer.codewritein "!=============================================================================================\n"
                        writer.codewritein("! Project name: " + projectname + "\n")
                        writer.codewritein("! Project version: " + codever + "\n")
                        writer.codewritein "!---------------------------------------------------------------------------------------------\n"
                        writer.codewritein "! Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)\n"
                        writer.codewritein("! Aqualis version: " + environment.Version + "\n")
                        writer.codewritein("! Generated date: " + System.DateTime.Now.ToString() + "\n")
                        writer.codewritein "!=============================================================================================\n"
                        writer.codewritein("program " + projectname + "\n")
                        writer.codewritein "use, intrinsic :: ieee_arithmetic\n"
                        //モジュールファイルのインクルード
                        List.iter (fun (s:string) -> writer.codewritein("use " + s + "\n")) <| context.CurrentProgram.mlist.list
                        writer.codewritein "implicit none\n"
                        //ヘッダファイルのインクルード
                        List.iter (fun (s:string) -> writer.codewritein("include " + s + "\n")) <| context.CurrentProgram.hlist.list
                        //構造体の定義
                        environment.str.Def_Structure writer
                        //グローバル変数の定義
                        declareall context writer
                        //メインコード
                        writer.codewritein(context.CurrentProgram.allCodes)
                        //サブルーチン
                        writer.codewritein "\n"
                        writer.codewritein "contains\n"
                        writer.codewritein "\n"
                        for funname in context.CurrentProgram.flist.list do
                            writer.codewritein(File.ReadAllText(dir + "\\" + funname + "_main"))
                            File.Delete(dir + "\\" + funname + "_main")
                            writer.codewritein "\n"
                        writer.codewritein("end program " + projectname + "\n")
                        writer.close()
                        //beeファイル削除
                        context.CurrentProgram.delete()
                        //コンパイル・実行用スクリプト生成
                        use wr = ShellScriptWriter.create(dir + "\\" + "proc_" + projectname + "_F.sh")
                        wr.WriteLine "#!/bin/bash"
                        wr.WriteLine()
                        let sources = context.CurrentProgram.slist.list
                        let options = context.CurrentProgram.olist.list
                        let writeCompileCommand compiler fixedArguments =
                            ShellCommand.buildCompileCommand
                                compiler
                                fixedArguments
                                sources
                                (projectname + ".f90")
                                options
                                (projectname + ".exe")
                            |> wr.WriteLine
                        if context.IsOpenAccUsed then
                            writeCompileCommand
                                "/usr/bin/pgfortran"
                                ["-acc"; "-Minfo=accel"]
                        else if context.IsOpenMpUsed then
                            writeCompileCommand
                                "/usr/bin/gfortran"
                                ["-fopenmp"]
                        else
                            writeCompileCommand
                                "/usr/bin/gfortran"
                                ["-ffree-line-length-none"]
                        ShellCommand.buildCommand
                            ("./" + projectname + ".exe")
                            []
                        |> wr.WriteLine
                |C99 ->
                    makeProgramWithContext [dir,projectname,C99] <| fun context ->
                        //メインコード生成
                        context.CurrentProgram.indentInc()
                        let environment = Aqualis(Some context)
                        code environment
                        context.CurrentProgram.olist.add "-lm"
                        context.CurrentProgram.indentDec()
                        context.CurrentProgram.close()
                        //ソースファイル出力
                        use writer = new codeWriter(dir + "\\" + projectname + ".c", 2, C99)
                        writer.codewritein "/*=============================================================================================*/\n"
                        writer.codewritein("/* Project name: " + projectname + " */\n")
                        writer.codewritein("/* Project version: " + codever + " */\n")
                        writer.codewritein "/*---------------------------------------------------------------------------------------------*/\n"
                        writer.codewritein "/* Generated by Aqualis (algorithm and equation analyzer for lightwave simulation) */\n"
                        writer.codewritein("/* Aqualis version: " + environment.Version + " */\n")
                        writer.codewritein("/* Generated date: " + System.DateTime.Now.ToString() + " */\n")
                        writer.codewritein "/*=============================================================================================*/\n"
                        writer.codewritein "#include <stdio.h>\n"
                        writer.codewritein "#include <stdlib.h>\n"
                        writer.codewritein "#include <complex.h>\n"
                        writer.codewritein "#include <math.h>\n"
                        //ヘッダファイルのインクルード
                        List.iter (fun (s:string) -> writer.codewritein ("#include " + s + "\n")) <| context.CurrentProgram.hlist.list
                        writer.codewritein "#undef I\n"
                        writer.codewritein "#define uj _Complex_I\n"
                        //構造体の定義
                        environment.str.Def_Structure writer
                        //グローバル変数の宣言
                        declareall context writer
                        //extern指定子
                        for s in context.CurrentProgram.elist.list do
                            writer.codewritein ("extern " + s + ";\n")
                        //関数定義
                        for funname in context.CurrentProgram.flist.list do
                            writer.codewritein (File.ReadAllText(dir + "\\" + funname + "_main"))
                            File.Delete(dir + "\\" + funname + "_main")
                            writer.codewritein ("\n")
                        //Main関数
                        writer.codewritein "int main()\n"
                        writer.codewritein "{\n"
                        writer.codewritein (context.CurrentProgram.allCodes)
                        writer.codewritein "  return 0;\n"
                        writer.codewritein "}\n"
                        writer.close()
                        //beeファイル削除
                        context.CurrentProgram.delete()
                        //コンパイル・実行用スクリプト生成
                        use wr = ShellScriptWriter.create(dir + "\\" + "proc_" + projectname + "_C.sh")
                        let sources = context.CurrentProgram.slist.list
                        let options = context.CurrentProgram.olist.list
                        let writeCompileCommand compiler fixedArguments =
                            ShellCommand.buildCompileCommand
                                compiler
                                fixedArguments
                                sources
                                (projectname + ".c")
                                options
                                (projectname + ".exe")
                            |> wr.WriteLine
                        if context.IsOpenMpUsed then
                            wr.Write "#!/bin/bash\n"
                            wr.Write "\n"
                            writeCompileCommand "gcc" ["-fopenmp"]
                            ShellCommand.buildCommand ("./" + projectname + ".exe") [] |> wr.WriteLine
                        else if context.IsOpenAccUsed then
                            wr.Write "#!/bin/bash"
                            wr.Write "\n"
                            writeCompileCommand "pgcc" ["-acc"; "-Minfo=accel"]
                            ShellCommand.buildCommand ("./" + projectname + ".exe") [] |> wr.WriteLine
                        else
                            wr.Write "#!/bin/bash\n"
                            wr.Write "\n"
                            writeCompileCommand "gcc" []
                            ShellCommand.buildCommand ("./" + projectname + ".exe") [] |> wr.WriteLine
                |LaTeX ->
                    makeProgramWithContext [dir,projectname,LaTeX] <| fun context ->
                        //メインコード生成
                        let environment = Aqualis(Some context)
                        code environment
                        context.CurrentProgram.close()
                        //ソースファイル出力
                        use writer = new codeWriter(dir + "\\" + projectname + ".tex", 2, LaTeX)
                        writer.codewritein "\\documentclass[a4paper,fleqn]{ltjsarticle}\n"
                        writer.codewritein "\\usepackage{amsmath}\n"
                        List.iter (fun (s:string) -> writer.codewritein(s + "\n")) <| context.CurrentProgram.hlist.list
                        writer.codewritein "\\oddsidemargin=-0.4mm\n"
                        writer.codewritein "\\topmargin=4.6mm\n"
                        writer.codewritein "\\headheight=0mm\n"
                        writer.codewritein "\\headsep=0mm\n"
                        writer.codewritein "\\footskip=15mm\n"
                        writer.codewritein "\\textwidth=160mm\n"
                        writer.codewritein "\\textheight=237mm\n"
                        writer.codewritein "\\topsep=6pt\n"
                        writer.codewritein "\\parindent=0mm\n"
                        writer.codewritein "\\unitlength=1.00mm\n"
                        writer.codewritein "\\begin{document}\n"
                        writer.codewritein("{\\Large " + projectname.Replace("_","\\_") + "}\n")
                        //構造体の定義
                        writer.codewritein "\\section{structures}\n"
                        environment.str.Def_Structure writer
                        //関数定義
                        writer.codewritein "\\section{subroutines}\n"
                        for funname in context.CurrentProgram.flist.list do
                            writer.codewritein(File.ReadAllText(dir + "\\" + funname + "_main"))
                            File.Delete(dir + "\\" + funname + "_main")
                            writer.codewritein("\n")
                        //グローバル変数の定義
                        writer.codewritein "\\section{global variables}\n"
                        writer.codewritein "\\begin{itemize}\n"
                        declareall context writer
                        writer.codewritein "\\end{itemize}\n"
                        //メインコード
                        writer.codewritein "\\section{main code}\n"
                        writer.codewritein(context.CurrentProgram.allCodes)
                        writer.codewritein "\\end{document}\n"
                        writer.close()
                        //beeファイル削除
                        context.CurrentProgram.delete()
                |HTML ->
                    makeProgramWithContext [dir,projectname,HTML] <| fun context ->
                        //メインコード生成
                        let environment = Aqualis(Some context)
                        code environment
                        context.CurrentProgram.close()
                        //ソースファイル出力
                        use writer = new codeWriter(dir + "\\" + projectname + ".html", 2, HTML)
                        writer.codewritein "<!DOCTYPE html>\n"
                        writer.codewritein "<html lang='ja'>\n"
                        writer.codewritein "\t<head>\n"
                        writer.codewritein "\t\t<meta charset='utf-8'>\n"
                        writer.codewritein "\t\t<script>\n"
                        writer.codewritein "\t\tMathJax = {\n"
                        writer.codewritein "\t\t\tchtml: {\n"
                        writer.codewritein "\t\t\t\tdisplayAlign: \"left\",\n"
                        writer.codewritein "\t\t\t}\n"
                        writer.codewritein "\t\t};\n"
                        writer.codewritein "\t\t</script>\n"
                        writer.codewritein "\t\t<script type=\"text/javascript\" id=\"MathJax-script\" async src=\"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js\"></script>\n"
                        writer.codewritein("\t\t<title>" + projectname + "</title>\n")
                        writer.codewritein "\t\t<meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0'>\n"
                        writer.codewritein "\t\t<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n"
                        writer.codewritein "\t\t<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n"
                        writer.codewritein "\t\t<link href=\"https://fonts.googleapis.com/css2?family=Noto + Sans + JP:wght@500;600;700&display=swap\" rel=\"stylesheet\">\n"
                        writer.codewritein "\t\t<style type=\"text/css\">\n"
                        writer.codewritein "\t\t<!--\n"
                        writer.codewritein "\t\tbody {\n"
                        writer.codewritein "\t\t\tfont-family: 'Noto Sans JP', sans-serif;\n"
                        writer.codewritein "\t\t\tfont-weight: 500;\n"
                        writer.codewritein "\t\t\tfont-size: 16px;\n"
                        writer.codewritein "\t\t}\n"
                        writer.codewritein "\t\th2 {\n"
                        writer.codewritein "\t\t\tborder-bottom: 2px solid;\n"
                        writer.codewritein "\t\t}\n"
                        writer.codewritein "\t\ta {\n"
                        writer.codewritein "\t\t\tfont-size: 11pt;\n"
                        writer.codewritein "\t\t\ttext-decoration: none;\n"
                        writer.codewritein "\t\t\tcolor: #8000ff;\n"
                        writer.codewritein "\t\t}\n"
                        writer.codewritein "\t\t.fio {\n"
                        writer.codewritein "\t\t\tmargin-right: 10px;\n"
                        writer.codewritein "\t\t\tfont-size: 11pt;\n"
                        writer.codewritein "\t\t\tcolor: #ff00ff;\n"
                        writer.codewritein "\t\t}\n"
                        writer.codewritein "\t\t.continue {\n"
                        writer.codewritein "\t\t\tfont-size: 11pt;\n"
                        writer.codewritein "\t\t\tcolor: #8000ff;\n"
                        writer.codewritein "\t\t}\n"
                        writer.codewritein "\t\t.codeblock {\n"
                        writer.codewritein "\t\t\tpadding-left: 0px;\n"
                        writer.codewritein "\t\t}\n"
                        writer.codewritein "\t\t\n"
                        writer.codewritein "\t\t.op-loop {\n"
                        writer.codewritein "\t\t\tfont-size: 11pt;\n"
                        writer.codewritein "\t\t\tcolor: #ff7f00;\n"
                        writer.codewritein "\t\t}\n"
                        writer.codewritein "\t\t\n"
                        writer.codewritein "\t\t.insidecode-loop {\n"
                        writer.codewritein "\t\t\tmargin-left: 2px;\n"
                        writer.codewritein "\t\t\tpadding-left: 30px;\n"
                        writer.codewritein "\t\t\tborder-left: solid;\n"
                        writer.codewritein "\t\t\tborder-width: 5px;\n"
                        writer.codewritein "\t\t\tborder-color: #ffa347;\n"
                        writer.codewritein "\t\t}\n"
                        writer.codewritein "\t\t\n"
                        writer.codewritein "\t\t.op-if {\n"
                        writer.codewritein "\t\t\tfont-size: 11pt;\n"
                        writer.codewritein "\t\t\tcolor: #007fff;\n"
                        writer.codewritein "\t\t}\n"
                        writer.codewritein "\t\t\n"
                        writer.codewritein "\t\t.insidecode-if {\n"
                        writer.codewritein "\t\t\tmargin-left: 2px;\n"
                        writer.codewritein "\t\t\tpadding-left: 30px;\n"
                        writer.codewritein "\t\t\tborder-left: solid;\n"
                        writer.codewritein "\t\t\tborder-width: 5px;\n"
                        writer.codewritein "\t\t\tborder-color: #47a3ff;\n"
                        writer.codewritein "\t\t}\n"
                        writer.codewritein "\t\t.op-func {\n"
                        writer.codewritein "\t\t\tfont-size: 11pt;\n"
                        writer.codewritein "\t\t\tcolor: #0000ff;\n"
                        writer.codewritein "\t\t}\n"
                        writer.codewritein "\t\t\n"
                        writer.codewritein "\t\t.insidecode-func {\n"
                        writer.codewritein "\t\t\tmargin-left: 2px;\n"
                        writer.codewritein "\t\t\tpadding-left: 30px;\n"
                        writer.codewritein "\t\t\tborder-left: solid;\n"
                        writer.codewritein "\t\t\tborder-width: 5px;\n"
                        writer.codewritein "\t\t\tborder-color: #0000ff;\n"
                        writer.codewritein "\t\t}\n"
                        writer.codewritein "\t\t.op-section {\n"
                        writer.codewritein "\t\t\tfont-size: 11pt;\n"
                        writer.codewritein "\t\t\tcolor: #008000;\n"
                        writer.codewritein "\t\t\tmargin-right: 5px;\n"
                        writer.codewritein "\t\t}\n"
                        writer.codewritein "\t\t\n"
                        writer.codewritein "\t\t.insidecode-section {\n"
                        writer.codewritein "\t\t\tmargin-left: 2px;\n"
                        writer.codewritein "\t\t\tpadding-left: 30px;\n"
                        writer.codewritein "\t\t\tborder-left: solid;\n"
                        writer.codewritein "\t\t\tborder-width: 5px;\n"
                        writer.codewritein "\t\t\tborder-color: #32cd32;\n"
                        writer.codewritein "\t\t}\n"
                        writer.codewritein "\t\t\n"
                        writer.codewritein "\t\t.comment {\n"
                        writer.codewritein "\t\t\tfont-size: 11pt;\n"
                        writer.codewritein "\t\t\tcolor: #008000;\n"
                        writer.codewritein "\t\t}\n"
                        writer.codewritein "\t\t-->\n"
                        writer.codewritein "\t\t</style>\n"
                        writer.codewritein "\t\t<script type=\"text/javascript\">\n"
                        writer.codewritein "\t\t\tfunction fsearch()\n"
                        writer.codewritein "\t\t\t{\n"
                        writer.codewritein "\t\t\t\t//var s = document.styleSheets.item(0);\n"
                        writer.codewritein "\t\t\t\t//s.cssRules[0].style.backgroundColor=\"blue\";\n"
                        writer.codewritein "\t\t\t\tvar vname = document.getElementById(\"textvar\").value;\n"
                        writer.codewritein "\t\t\t\tvar targets = document.getElementsByClassName(vname);\n"
                        writer.codewritein "\t\t\t\tfor (i = 0; i < targets.length; i++)\n"
                        writer.codewritein "\t\t\t\t{\n"
                        writer.codewritein "\t\t\t\t\ttargets[i].style.color =  '#ff0000';\n"
                        writer.codewritein "\t\t\t\t}\n"
                        writer.codewritein "\t\t\t}\n"
                        writer.codewritein "\t\t</script>\n"
                        writer.codewritein "\t</head>\n"
                        writer.codewritein "\t<body>\n"
                        writer.codewritein("\t\t<h1>" + projectname + "</h1>\n")
                        writer.codewritein "\t\t<div id=\"codeinfo\">\n"
                        writer.codewritein "\t\t\t<ul>\n"
                        writer.codewritein("\t\t\t\t<li>Project version: " + codever + "</li>\n")
                        writer.codewritein "\t\t\t\t<li>Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)</li>\n"
                        writer.codewritein("\t\t\t\t<li>Aqualis version: " + environment.Version + "</li>\n")
                        writer.codewritein("\t\t\t\t<li>Generated date: " + System.DateTime.Now.ToString() + "</li>\n")
                        writer.codewritein "\t\t\t</ul>\n"
                        writer.codewritein "\t\t</div>\n"
                        //構造体の定義
                        writer.codewritein "\t\t<div id=\"defstr\">\n"
                        writer.codewritein "\t\t<h2>構造体定義</h2>\n"
                        environment.str.Def_Structure writer
                        writer.codewritein "\t\t</div>\n"
                        //関数定義
                        writer.codewritein "\t\t<div id=\"deffunc\">\n"
                        writer.codewritein "\t\t<h2>関数定義</h2>\n"
                        for funname in context.CurrentProgram.flist.list do
                            writer.codewritein(File.ReadAllText(dir + "\\" + funname + "_main"))
                            File.Delete(dir + "\\" + funname + "_main")
                            writer.codewritein "\n"
                        writer.codewritein "\t\t</div>\n"
                        //グローバル変数の定義
                        writer.codewritein "\t\t<div id=\"defvar\">\n"
                        writer.codewritein "\t\t<h2>グローバル変数</h2>\n"
                        writer.codewritein "\t\t<ul>\n"
                        declareall context writer
                        writer.codewritein "\t\t</ul>\n"
                        writer.codewritein "\t\t</div>\n"
                        //メインコード
                        writer.codewritein "\t\t<div id=\"maincode\">\n"
                        writer.codewritein "\t\t<h2>メインコード</h2>\n"
                        writer.codewritein "<input type=\"text\" id=\"textvar\" value=\"\">\n"
                        writer.codewritein "<input type=\"button\" onclick=\"fsearch()\" value=\"Search\">\n"
                        writer.codewritein "<br/>\n"
                        writer.codewritein(context.CurrentProgram.allCodes)
                        writer.codewritein "\t\t</div>\n"
                        writer.codewritein "\t</body>\n"
                        writer.codewritein "</html>\n"
                        writer.close()
                        //beeファイル削除
                        context.CurrentProgram.delete()
                |HTMLSequenceDiagram ->
                    // ディレクトリ作成
                    if not <| Directory.Exists (dir + "\\" + "contents_" + projectname) then
                        ignore <| Directory.CreateDirectory(dir + "\\" + "contents_" + projectname)
                    // コンテンツディレクトリ
                    makeProgramWithContext
                        [
                            // メインファイル
                            dir, projectname + ".html", HTMLSequenceDiagram
                            // HTML本体のコード
                            dir, projectname + "_body", HTMLSequenceDiagram
                        ]
                        <| fun context ->
                            let environment = Aqualis(Some context)
                            context.ContentsDirectory <-
                                dir + "\\" + "contents_" + projectname
                            environment.htmlio.switchBody <| fun bodyEnvironment ->
                                code bodyEnvironment
                            let codeBody = environment.htmlio.switchBody <| fun bodyEnvironment ->
                                bodyEnvironment.RequireGenerationContext().CurrentProgram.allCodes
                            // html書き込みストリーム作成
                            environment.htmlio.switchMain <| fun environment ->
                                let context = environment.RequireGenerationContext()
                                writein context "<!DOCTYPE html>"
                                // html要素
                                environment.html.tagb ("html", "lang=\"ja\"") <| fun () ->
                                    // head要素
                                    environment.html.tagb ("head", "") <| fun () ->
                                        // titleタグ
                                        writein context ("<title>"+projectname+"</title>")
                                        // metaタグ
                                        writein context "<meta charset=\"UTF-8\">"
                                        //追加（5/29）viewportタブ
                                        writein context "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0\">"
                                        // titleタグ
                                        environment.html.tagb ("title", "") <| fun () ->
                                            writein context projectname
                                        // MathJax
                                        environment.html.tagb ("script", "type=\"text/javascript\" id=\"MathJax-script\" async src=\"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js\"") <| fun () -> ()
                                        environment.html.tagb ("script", "type=\"text/javascript\" src=\"" + "contents_" + projectname + "/animationSeq.js\"") <| fun () -> ()
                                        environment.html.tagb ("script", "type=\"text/javascript\" src=\"" + "contents_" + projectname + "/animationSeqReset.js\"") <| fun () -> ()
                                        environment.html.tagb ("script", "type=\"text/javascript\" src=\"" + "contents_" + projectname + "/animationStart.js\"") <| fun () -> ()
                                        environment.html.tagb ("script", "type=\"text/javascript\" src=\"" + "contents_" + projectname + "/animationReset.js\"") <| fun () -> ()
                                        environment.html.tagb ("script", "type=\"text/javascript\" src=\"" + "contents_" + projectname + "/autoAnimation.js\"") <| fun () -> ()
                                        // webフォント取得
                                        writein context "<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">"
                                        writein context "<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>"
                                        writein context "<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100..900&display=swap\" rel=\"stylesheet\">"
                                    // body要素
                                    let s0 = Style [area.backGroundColor "#ffffff"]
                                    environment.html.tagb ("body", [s0.atr]) <| fun () ->
                                        writein context codeBody
                            for i in 0..1 do
                                context.Programs[i].close()
                            // bodyタグ一時コード削除
                            context.Programs[1].delete()
                |Python ->
                    makeProgramWithContext [dir,projectname,Python] <| fun context ->
                        //メインコード生成
                        let environment = Aqualis(Some context)
                        code environment
                        context.CurrentProgram.close()
                        //ソースファイル出力
                        use writer = new codeWriter(dir + "\\" + projectname + ".py", 2, Python)
                        writer.codewritein "#=============================================================================================\n"
                        writer.codewritein("# Project name: " + projectname + "\n")
                        writer.codewritein("# Project version: " + codever + "\n")
                        writer.codewritein "#---------------------------------------------------------------------------------------------\n"
                        writer.codewritein "# Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)\n"
                        writer.codewritein("# Aqualis version: " + environment.Version + "\n")
                        writer.codewritein("# Generated date: " + System.DateTime.Now.ToString() + "\n")
                        writer.codewritein "#=============================================================================================\n"
                        //次のコマンドを打って、NumPyとSciPyをインストール
                        //pip install numpy scipy
                        writer.codewritein "import numpy\n"
                        writer.codewritein "import math\n"
                        writer.codewritein "import cmath\n"
                        writer.codewritein "import copy\n"
                        writer.codewritein "import struct\n"
                        writer.codewritein "import re\n"
                        writer.codewritein "from scipy.linalg import solve, svd, eig, lu\n"
                        writer.codewritein "from scipy.special import jv, yn\n"
                        writer.codewritein "import sys\n"
                        //ヘッダファイルのインクルード
                        List.iter (fun (s:string) -> writer.codewritein("import " + s + "\n")) <| context.CurrentProgram.hlist.list
                        //構造体の定義
                        environment.str.Def_Structure writer
                        //グローバル変数の定義
                        declareall context writer
                        //関数定義
                        for funname in context.CurrentProgram.flist.list do
                            writer.codewritein(File.ReadAllText(dir + "\\" + funname + "_main"))
                            File.Delete(dir + "\\" + funname + "_main")
                            writer.codewritein("\n")
                        //メインコード
                        writer.codewritein(context.CurrentProgram.allCodes)
                        writer.close()
                        //beeファイル削除
                        context.CurrentProgram.delete()
                        use wr = ShellScriptWriter.create(dir + "\\" + "proc_" + projectname + "_P.sh")
                        wr.Write "#!/bin/bash\n"
                        wr.Write "\n"
                        wr.Write("python3 " + projectname + ".py\n")
                |JavaScript ->
                    makeProgramWithContext [dir,projectname,JavaScript] <| fun context ->
                        //メインコード生成
                        context.CurrentProgram.indentInc()
                        let environment = Aqualis(Some context)
                        code environment
                        context.CurrentProgram.indentDec()
                        context.CurrentProgram.close()
                        //ソースファイル出力
                        use writer = new codeWriter(dir + "\\" + projectname + ".c", 2, C99)
                        writer.codewritein "/*=============================================================================================*/\n"
                        writer.codewritein("/* Project name: " + projectname + " */\n")
                        writer.codewritein("/* Project version: " + codever + " */\n")
                        writer.codewritein "/*---------------------------------------------------------------------------------------------*/\n"
                        writer.codewritein "/* Generated by Aqualis (algorithm and equation analyzer for lightwave simulation) */\n"
                        writer.codewritein("/* Aqualis version: " + environment.Version + " */\n")
                        writer.codewritein("/* Generated date: " + System.DateTime.Now.ToString() + " */\n")
                        writer.codewritein "/*=============================================================================================*/\n"
                        writer.codewritein "#include <stdio.h>\n"
                        writer.codewritein "#include <stdlib.h>\n"
                        writer.codewritein "#include <complex.h>\n"
                        writer.codewritein "#include <math.h>\n"
                        //ヘッダファイルのインクルード
                        List.iter (fun (s:string) -> writer.codewritein ("#include " + s + "\n")) <| context.CurrentProgram.hlist.list
                        writer.codewritein "#undef I\n"
                        writer.codewritein "#define uj _Complex_I\n"
                        //構造体の定義
                        environment.str.Def_Structure writer
                        //グローバル変数の宣言
                        declareall context writer
                        //extern指定子
                        for s in context.CurrentProgram.elist.list do
                            writer.codewritein ("extern " + s + ";\n")
                        //関数定義
                        for funname in context.CurrentProgram.flist.list do
                            writer.codewritein (File.ReadAllText(dir + "\\" + funname + "_main"))
                            File.Delete(dir + "\\" + funname + "_main")
                            writer.codewritein ("\n")
                        //Main
                        writer.codewritein (context.CurrentProgram.allCodes)
                        writer.close()
                        //beeファイル削除
                        context.CurrentProgram.delete()
                |PHP ->
                    makeProgramWithContext [dir,projectname + ".php",PHP] <| fun context ->
                        let environment = Aqualis(Some context)
                        code environment
                        context.CurrentProgram.close()
                |Numeric -> code (Aqualis None)
