!=============================================================================================
! Project name: test0
! Project version: bbb
!---------------------------------------------------------------------------------------------
! Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)
! Aqualis version: aaa
! Generated date: 2026/01/13 13:00:59
!=============================================================================================
program test0
implicit none
character(100) :: t0002
integer :: f0001=12
integer :: tab=2313
integer(1) :: byte_tmp
character(100) :: t0001
integer :: f0000=11
complex(kind(0d0)) :: uj=(0d0,1d0)
double precision :: pi=3.14159265358979d0
complex(kind(0d0)) :: z
double precision :: y
integer :: x
integer :: i
integer :: i0001
integer :: i0002
integer :: i0003
double precision :: d0001
double precision :: d0002
complex(kind(0d0)) :: z0001
integer,allocatable :: i1001(:)
integer :: i1001_size(1:1) = (/ -1 /)
x = 1
y = pi
z = uj
do i0003=0,9
  i = i0001+i+i0002
end do
do i0003=0,9
  i = i0001+i+i0002
end do
do i0003=0,9
  i = i0001+i+i0002
end do
i0001 = 1
if((i0001 < i0002 .and. i0002 < i0003) .or. i0003 < 1) then
  i0001 = 0
endif
i0002 = 2
i0003 = 3
print *, i0001
print *, i0001,i0002,i0003
print *, "aaa"
print *, i0001,i0002,i0003
print *, i0001,i0002,i0003
print *, i0001,"aaa",i0002,"bbb",i0003
write(t0001,"(A)") "test.dat"
do i0001 = 1, len_trim(t0001)
  if ( t0001( i0001:i0001 ).EQ." " ) t0001( i0001:i0001 ) = "0"
end do
open(f0000, file=trim(t0001))
z0001 = 1+uj*2
write(f0000,"(E27.12e3,A1,E27.12e3)") real(z0001),tab,aimag(z0001)
close(f0000)
write(t0002,"(A)") "test.dat"
do i0002 = 1, len_trim(t0002)
  if ( t0002( i0002:i0002 ).EQ." " ) t0002( i0002:i0002 ) = "0"
end do
open(f0001, file=trim(t0002))
read(f0001,"(E27.12e3,A1,E27.12e3)",iostat=i0001) d0001,i0002,d0002
z0001 = d0001+uj*d0002
print *, real(z0001),aimag(z0001)
close(f0001)
i1001_size(1) = 10
allocate(i1001(1:i1001_size(1)))
i1001(1) = 0
i1001_size(1) = -1
deallocate(i1001)
contains
end program test0
