!=============================================================================================
! Project name: test0
! Project version: bbb
!---------------------------------------------------------------------------------------------
! Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)
! Aqualis version: aaa
! Generated date: 2025/12/28 14:21:41
!=============================================================================================
program test0
implicit none
double precision :: pi=3.14159265358979d0
double precision :: y
double precision :: x
double precision :: d0001
double precision,allocatable :: d1001(:)
integer :: d1001_size(1:1) = (/ -1 /)
complex(kind(0d0)),allocatable :: z2001(:,:)
integer :: z2001_size(1:2) = (/ -1,-1 /)
x = pi
!test
y = 1
d1001_size(1) = 10
allocate(d1001(1:d1001_size(1)))
z2001_size(1) = 10
z2001_size(2) = 20
allocate(z2001(1:z2001_size(1),1:z2001_size(2)))
d0001 = 1.234d0
z2001_size(1) = -1
z2001_size(2) = -1
deallocate(z2001)
d1001_size(1) = -1
deallocate(d1001)
contains
end program test0
