#=============================================================================================
# Project name: test0
# Project version: bbb
#---------------------------------------------------------------------------------------------
# Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)
# Aqualis version: 188.0.0.0
# Generated date: 2026/08/24 13:17:44
#=============================================================================================
import numpy
import math
import cmath
import copy
import struct
import re
from scipy.linalg import solve, svd, eig, lu
from scipy.special import jv, yn
import sys
t0001 = 0
f0000 = 0
byte_tmp = 0
t0001 = 0
f0000 = 0
z = 0
y = 0
x = 0
i = 0
i0001 = 0
i0002 = 0
i0003 = 0
d0001 = 0
d0002 = 0
z0001 = 0
i1001 = numpy.array([])
i1001_size = numpy.array([-1])
x = 1
y = 3.14159265358979E0
z = uj
for i0003 in range(0, 10, 1):
  i = i0001+i+i0002
for i0003 in range(0, 10, 1):
  i = i0001+i+i0002
for i0003 in range(0, 10, 1):
  i = i0001+i+i0002
i0001 = 1
if (i0001 < i0002 and i0002 < i0003) or i0003 < 1:
  i0001 = 0
i0002 = 2
i0003 = 3
print("%12d" %(i0001))
print("aaa")
print("%12d%12d%12d" %(i0001,i0002,i0003))
print("%12daaa%12dbbb%12d" %(i0001,i0002,i0003))
t0001= "test.dat"%()
f0000 = open(t0001,mode="w")
z0001 = 1.0E0+uj*2.0E0
f0000.write("%27.17e\t%27.17e\n" %((z0001).real,(z0001).imag))
f0000.close()
t0001= "test.dat"%()
f0000 = open(t0001,mode="r")
lines = f0000.readline()
word_list = re.split(r'[\t\n]', lines)
z0001 = complex(float(word_list[0]),float(word_list[1]))
print("%27.17e%27.17e" %((z0001).real,(z0001).imag))
f0000.close()
i1001_size[0] = 10
i1001 = numpy.zeros(i1001_size[0], dtype=int)
i1001[0] = 0
i1001_size[0] = -1
del i1001
