#=============================================================================================
# Project name: test0
# Project version: bbb
#---------------------------------------------------------------------------------------------
# Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)
# Aqualis version: aaa
# Generated date: 2025/12/28 14:21:41
#=============================================================================================
import numpy
import math
import cmath
import copy
import struct
import re
from scipy.linalg import solve, svd, eig, lu
from scipy.special import jv, yn
import sys
pi = 3.14159265358979
y = 0
x = 0
d0001 = 0
d1001 = numpy.array([])
d1001_size = numpy.array([-1])
z2001 = numpy.array([[]], dtype=int)
z2001_size = numpy.array([-1])
x = pi
#test
y = 1
d1001_size[0] = 10
d1001 = numpy.zeros(d1001_size[0])
z2001_size[0] = 10
z2001_size[1] = 20
z2001 = numpy.zeros(z2001_size[0]*z2001_size[1], dtype=numpy.complex128).reshape(int(z2001_size[0]),int(z2001_size[1]))
d0001 = 1.234E0
z2001_size[0] = -1
z2001_size[1] = -1
del z2001
d1001_size[0] = -1
del d1001
