/*=============================================================================================*/
/* Project name: test0 */
/* Project version: bbb */
/*---------------------------------------------------------------------------------------------*/
/* Generated by Aqualis (algorithm and equation analyzer for lightwave simulation) */
/* Aqualis version: aaa */
/* Generated date: 2026/01/13 13:00:59 */
/*=============================================================================================*/
#include <stdio.h>
#include <stdlib.h>
#include <complex.h>
#include <math.h>
#undef I
#define uj _Complex_I
char t0002[100];
FILE* f0001;
char byte_tmp;
char t0001[100];
FILE* f0000;
double pi = 3.14159265358979;
double complex z;
double y;
int x;
int i;
int i0001;
int i0002;
int i0003;
double d0001;
double d0002;
double complex z0001;
int *i1001;
int i1001_size[1] = { -1 };
int main()
{
  x = 1;
  y = pi;
  z = uj;
  for(i0003=0; i0003<=9; i0003++)
  {
    i = i0001+i+i0002;
  }
  for(i0003=0; i0003<=9; i0003++)
  {
    i = i0001+i+i0002;
  }
  for(i0003=0; i0003<=9; i0003++)
  {
    i = i0001+i+i0002;
  }
  i0001 = 1;
  if((i0001 < i0002 && i0002 < i0003) || i0003 < 1)
  {
    i0001 = 0;
  }
  i0002 = 2;
  i0003 = 3;
  printf("%8d\n",i0001);
  printf("%8d%8d%8d\n",i0001,i0002,i0003);
  printf("aaa");
  printf("%8d%8d%8d\n",i0001,i0002,i0003);
  printf("%8d%8d%8d\n",i0001,i0002,i0003);
  printf("%8daaa%8dbbb%8d\n",i0001,i0002,i0003);
  sprintf(t0001,"test.dat");
  f0000 = fopen(t0001,"w");
  z0001 = 1+uj*2;
  fprintf(f0000,"%27.12e\t%27.12e\n",creal(z0001),cimag(z0001));
  fclose(f0000);
  sprintf(t0002,"test.dat");
  f0001 = fopen(t0002,"r");
  fscanf(f0001,"%lf%lf",&d0001,&d0002);
  z0001 = d0001+uj*d0002;
  printf("%27.12e%27.12e\n",creal(z0001),cimag(z0001));
  fclose(f0001);
  i1001_size[0] = 10;
  i1001 = (int *)malloc(sizeof(int)*i1001_size[0]);
  i1001[0] = 0;
  i1001_size[0] = -1;
  free(i1001);
  return 0;
}
