#=============================================================================================
# Project name: test3_1
# Project version: aaa
#---------------------------------------------------------------------------------------------
# Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)
# Aqualis version: aaa
# Generated date: 2025/12/28 15:04:43
#=============================================================================================
import numpy
import math
import cmath
import copy
import struct
import re
from scipy.linalg import solve, svd, eig, lu
from scipy.special import jv, yn
import sys
class testClass1:
  x1 = 0
  y1 = 0
  x2 = 0
xx = numpy.array([])
xx_size = numpy.array([-1])
d = numpy.array([], dtype=object)
d_size = numpy.array([-1])
c = testClass1()
i0001 = 0
i1001 = numpy.array([])
i1001_size = numpy.array([-1])
c.x1 = 1
c.y1 = 2.0E0
c.x2 = 3.0E0+1.0j*4.0E0
print("%8d" %(c.x1))
print("%27.12e" %(c.y1))
print("%27.12e%27.12e" %((c.x2).real,(c.x2).imag))
d_size[0] = 4
d = numpy.array([testClass1() for _ in range(int(d_size[0]))], dtype=object)
xx_size[0] = 8
xx = numpy.zeros(xx_size[0], dtype=int)
for i0001 in range(0, d_size[0], 1):
  d[i0001].x1 = 1
  d[i0001].y1 = 2.0E0
  d[i0001].x2 = 3.0E0+1.0j*4.0E0
i1001_size[0] = 10
i1001 = numpy.zeros(i1001_size[0], dtype=int)
i1001[0] = 0
i1001[1] = 1
i1001[2] = 2
i1001[3] = 3
i1001_size[0] = -1
del i1001
i1001_size[0] = 20
i1001 = numpy.zeros(i1001_size[0], dtype=int)
i1001[0] = 0
i1001[1] = 1
i1001[2] = 2
i1001[3] = 3
i1001_size[0] = -1
del i1001
