#=============================================================================================
# Project name: test3_2
# Project version: aaa
#---------------------------------------------------------------------------------------------
# Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)
# Aqualis version: aaa
# Generated date: 2026/01/13 13:03:58
#=============================================================================================
import numpy
import math
import cmath
import copy
import struct
import re
from scipy.linalg import solve, svd, eig, lu
from scipy.special import jv, yn
import sys
class testClass1:
  n1 = 0
  x1 = 0
  z1 = 0
class testClass2:
  s2 = testClass1()
  t2 = numpy.array([], dtype=object)
  t2_size = numpy.zeros(1,dtype=int)
q = numpy.array([], dtype=object)
q_size = numpy.array([-1])
p = testClass2()
xx = numpy.array([])
xx_size = numpy.array([-1])
d = numpy.array([], dtype=object)
d_size = numpy.array([-1])
i0001 = 0
i1001 = numpy.array([])
i1001_size = numpy.array([-1])
d_size[0] = 4
d = numpy.array([testClass1() for _ in range(int(d_size[0]))], dtype=object)
xx_size[0] = 8
xx = numpy.zeros(xx_size[0], dtype=int)
p.s2.n1 = 100
p.s2.x1 = 2.0E2
p.s2.z1 = 3.0E2+1.0j*4.0E2
p.t2_size[0] = 3
p.t2 = numpy.array([testClass1() for _ in range(int(p.t2_size[0]))], dtype=object)
q_size[0] = 5
q = numpy.array([testClass2() for _ in range(int(q_size[0]))], dtype=object)
q[0].t2_size[0] = 2
q[0].t2 = numpy.array([testClass1() for _ in range(int(q[0].t2_size[0]))], dtype=object)
q[0].t2[1].n1 = 2000
print("%8d" %(q[0].t2[1].n1))
p.t2[0].n1 = 1000
for i0001 in range(0, d_size[0], 1):
  d[i0001].n1 = 1
  d[i0001].x1 = 2.0E0
  d[i0001].z1 = 3.0E0+1.0j*4.0E0
i1001_size[0] = 10
i1001 = numpy.zeros(i1001_size[0], dtype=int)
i1001[0] = 0
i1001[1] = 1
i1001[2] = 2
i1001[3] = 3
i1001_size[0] = -1
del i1001
i1001_size[0] = 20
i1001 = numpy.zeros(i1001_size[0], dtype=int)
i1001[0] = 0
i1001[1] = 1
i1001[2] = 2
i1001[3] = 3
i1001_size[0] = -1
del i1001
print("%8d" %(p.s2.n1))
print("%27.12e" %(p.s2.x1))
print("%27.12e%27.12e" %((p.s2.z1).real,(p.s2.z1).imag))
