!=============================================================================================
! Project name: test3_1
! Project version: aaa
!---------------------------------------------------------------------------------------------
! Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)
! Aqualis version: aaa
! Generated date: 2026/01/13 13:03:43
!=============================================================================================
program test3_1
implicit none
type testClass1
  integer :: x1
  double precision :: y1
  complex(kind(0d0)) :: x2
end type testClass1
integer,allocatable :: xx(:)
integer :: xx_size(1:1) = (/ -1 /)
type(testClass1),allocatable :: d(:)
integer :: d_size(1:1) = (/ -1 /)
complex(kind(0d0)) :: uj=(0d0,1d0)
type(testClass1) :: c
integer :: i0001
integer,allocatable :: i1001(:)
integer :: i1001_size(1:1) = (/ -1 /)
c%x1 = 1
c%y1 = 2.0d0
c%x2 = 3.0d0+uj*4.0d0
print *, c%x1
print *, c%y1
print *, real(c%x2),aimag(c%x2)
d_size(1) = 4
allocate(d(1:d_size(1)))
xx_size(1) = 8
allocate(xx(1:xx_size(1)))
do i0001=0,d_size(1)-1
  d(i0001+1)%x1 = 1
  d(i0001+1)%y1 = 2.0d0
  d(i0001+1)%x2 = 3.0d0+uj*4.0d0
end do
i1001_size(1) = 10
allocate(i1001(1:i1001_size(1)))
i1001(1) = 0
i1001(2) = 1
i1001(3) = 2
i1001(4) = 3
i1001_size(1) = -1
deallocate(i1001)
i1001_size(1) = 20
allocate(i1001(1:i1001_size(1)))
i1001(1) = 0
i1001(2) = 1
i1001(3) = 2
i1001(4) = 3
i1001_size(1) = -1
deallocate(i1001)
contains
end program test3_1
