!=============================================================================================
! Project name: test2
! Project version: aaa
!---------------------------------------------------------------------------------------------
! Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)
! Aqualis version: aaa
! Generated date: 2026/01/13 13:03:03
!=============================================================================================
program test2
implicit none
complex(kind(0d0)) :: uj=(0d0,1d0)
integer :: i0001
integer :: i0002
double precision :: d0001
double precision :: d0002
double precision :: d0003
complex(kind(0d0)) :: z0001
complex(kind(0d0)) :: z0002
double precision,allocatable :: d1001(:)
integer :: d1001_size(1:1) = (/ -1 /)
double precision,allocatable :: d1002(:)
integer :: d1002_size(1:1) = (/ -1 /)
double precision,allocatable :: d1003(:)
integer :: d1003_size(1:1) = (/ -1 /)
double precision,allocatable :: d2001(:,:)
integer :: d2001_size(1:2) = (/ -1,-1 /)
double precision,allocatable :: d2002(:,:)
integer :: d2002_size(1:2) = (/ -1,-1 /)
double precision,allocatable :: d2003(:,:)
integer :: d2003_size(1:2) = (/ -1,-1 /)
!%%%testA%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  !001
  i0002 = 1
  i0001 = 2
  d0001 = 3.0d0
  d0002 = 4.0d0
  !002
  i0001 = i0002+1
  !003
  i0001 = i0001+i0002
  !004
  i0001 = (i0001+i0002)*(i0001+i0002)
  !005
  d0001 = 1
  !006
  d0002 = d0001/d0002/d0002
  !007
  i0001 = i0001-i0002
  !008
  d0001 = dble(i0001)/dble(i0002)
  !009
  i0001 = i0001/i0002
  !010
  print *, i0002
  print *, i0002
  print *, i0002+1
  !011
  i0002 = -1
  !012
  i0001 = 1-i0002
  !013
  i0001 = i0002-i0001
  !014
  i0001 = -(i0001+i0002)*(i0001+i0002)
  !015
  d0001 = -1
  !016
  d0002 = -d0001/d0002/d0002
  !017
  i0001 = -(i0001+i0002)
  !018
  d0001 = -dble(i0001)/dble(i0002)
  !019
  i0001 = -i0001/i0002
  !020
  d0001 = 2.0d0*i0001
  !021
  i0001 = 2*i0001
  !022
  d0001 = 7.45d-1
  d0002 = sin(-(d0001+d0002)/d0001)
  d0002 = cos(d0001)
  d0002 = tan(d0001)
  d0002 = exp(d0001)
  d0002 = log(d0001)
  d0002 = log10(d0001)
  d0002 = sqrt(d0001)
  d0002 = asin(d0001)
  d0002 = acos(d0001)
  d0002 = atan(d0001)
  d0002 = atan2(d0001,d0002)
  d0002 = floor(d0001)
  d0002 = ceiling(d0001)
!%%%end testA%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
!%%%testB%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  d1001_size(1) = 10
  allocate(d1001(1:d1001_size(1)))
  d1002_size(1) = 10
  allocate(d1002(1:d1002_size(1)))
  d1003_size(1) = 10
  allocate(d1003(1:d1003_size(1)))
  !021
  do i0001=0,d1003_size(1)-1
    d1003(i0001+1) = d1001(i0001+1)+d1002(i0001+1)
  end do
  !022
  do i0001=0,2
    d1003(2+i0001) = d1001(5+i0001)+d1002(5+i0001)
  end do
  !023
  do i0001=0,d1003_size(1)-1
    d1003(i0001+1) = d1001(i0001+1)*(d1001(i0001+1)+d1002(i0001+1))
  end do
  d1003_size(1) = -1
  deallocate(d1003)
  d2001_size(1) = 10
  d2001_size(2) = 5
  allocate(d2001(1:d2001_size(1),1:d2001_size(2)))
  d2002_size(1) = 10
  d2002_size(2) = 5
  allocate(d2002(1:d2002_size(1),1:d2002_size(2)))
  d2003_size(1) = 10
  d2003_size(2) = 5
  allocate(d2003(1:d2003_size(1),1:d2003_size(2)))
  !024
  do i0001=0,d2003_size(1)-1
    do i0002=0,d2003_size(2)-1
      d2003(i0001+1,i0002+1) = d2001(i0001+1,i0002+1)+d2002(i0001+1,i0002+1)
    end do
  end do
  !025
  do i0001=0,2
    d2003(2+i0001,4) = d2001(5+i0001,4)+d2002(5+i0001,4)
  end do
  !026
  do i0001=0,d2003_size(1)-1
    do i0002=0,d2003_size(2)-1
      d2003(i0001+1,i0002+1) = d2001(i0001+1,i0002+1)*(d2001(i0001+1,i0002+1)+d2002(i0001+1,i0002+1))
    end do
  end do
  d2003_size(1) = -1
  d2003_size(2) = -1
  deallocate(d2003)
  !027
  i0001 = 1
  !028
  i0001 = 1
  i0002 = 1
  i0002 = 8*i0001
  !aaa
  d0001 = 2.0d0*i0001
  !bbb
  i0002 = 2*i0001
  !ccc
  d2002_size(1) = -1
  d2002_size(2) = -1
  deallocate(d2002)
  d2001_size(1) = -1
  d2001_size(2) = -1
  deallocate(d2001)
  d1002_size(1) = -1
  deallocate(d1002)
  d1001_size(1) = -1
  deallocate(d1001)
!%%%end testB%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
!%%%testC%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  !001
  i0001 = 2*i0001
  !002
  i0001 = 0
  !003
  d0001 = 1
  !004
  i0001 = 1
  !005
  d0001 = 2*(i0001+d0001)
  !006
  d0001 = 4*i0001
  !007
  d0001 = 0
  !008
  d0001 = 0
  !009
  d0001 = 1
  !010
  d0001 = 1
  !011
  d0001 = 1
!%%%end testC%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
!%%%testD%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  !001
  print *, "001"
  d0001 = 1
  d0002 = sin(d0001)
  print *, d0002
  d0002 = cos(d0001)
  print *, d0002
  d0002 = tan(d0001)
  print *, d0002
  d0002 = exp(d0001)
  print *, d0002
  d0002 = log(d0001)
  print *, d0002
  d0002 = log10(d0001)
  print *, d0002
  d0002 = sqrt(d0001)
  print *, d0002
  d0002 = asin(d0001)
  print *, d0002
  d0002 = acos(d0001)
  print *, d0002
  d0002 = atan(d0001)
  print *, d0002
  d0002 = atan2(d0001,d0002)
  print *, d0002
  !002
  print *, "002"
  d0001 = 2.8d-1
  d0003 = sin(d0001)
  print *, d0003
  d0003 = cos(d0001)
  print *, d0003
  d0003 = tan(d0001)
  print *, d0003
  d0003 = exp(d0001)
  print *, d0003
  d0003 = log(d0001)
  print *, d0003
  d0003 = log10(d0001)
  print *, d0003
  d0003 = sqrt(d0001)
  print *, d0003
  d0003 = asin(d0001)
  print *, d0003
  d0003 = acos(d0001)
  print *, d0003
  d0003 = atan(d0001)
  print *, d0003
  d0003 = atan2(d0001,d0002)
  print *, d0003
  d0003 = floor(d0001)
  print *, d0003
  d0003 = ceiling(d0001)
  print *, d0003
  !003
  print *, "003"
  z0001 = 1.0d0-uj*2.0d0
  z0002 = sin(z0001)
  print *, real(z0002),aimag(z0002)
  z0002 = cos(z0001)
  print *, real(z0002),aimag(z0002)
  z0002 = tan(z0001)
  print *, real(z0002),aimag(z0002)
  z0002 = exp(z0001)
  print *, real(z0002),aimag(z0002)
  z0002 = log(z0001)
  print *, real(z0002),aimag(z0002)
  z0002 = sqrt(z0001)
  print *, real(z0002),aimag(z0002)
  z0002 = asin(z0001)
  print *, real(z0002),aimag(z0002)
  z0002 = acos(z0001)
  print *, real(z0002),aimag(z0002)
  z0002 = atan(z0001)
  print *, real(z0002),aimag(z0002)
!%%%end testD%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
contains
end program test2
