#=============================================================================================
# Project name: test2
# Project version: aaa
#---------------------------------------------------------------------------------------------
# Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)
# Aqualis version: aaa
# Generated date: 2026/01/13 13:03:03
#=============================================================================================
import numpy
import math
import cmath
import copy
import struct
import re
from scipy.linalg import solve, svd, eig, lu
from scipy.special import jv, yn
import sys
i0001 = 0
i0002 = 0
d0001 = 0
d0002 = 0
d0003 = 0
z0001 = 0
z0002 = 0
d1001 = numpy.array([])
d1001_size = numpy.array([-1])
d1002 = numpy.array([])
d1002_size = numpy.array([-1])
d1003 = numpy.array([])
d1003_size = numpy.array([-1])
d2001 = numpy.array([[]], dtype=int)
d2001_size = numpy.array([-1,-1])
d2002 = numpy.array([[]], dtype=int)
d2002_size = numpy.array([-1,-1])
d2003 = numpy.array([[]], dtype=int)
d2003_size = numpy.array([-1,-1])
#%%%testA%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#001
i0002 = 1
i0001 = 2
d0001 = 3.0E0
d0002 = 4.0E0
#002
i0001 = i0002+1
#003
i0001 = i0001+i0002
#004
i0001 = (i0001+i0002)*(i0001+i0002)
#005
d0001 = 1
#006
d0002 = d0001/d0002/d0002
#007
i0001 = i0001-i0002
#008
d0001 = float(i0001)/float(i0002)
#009
i0001 = i0001/i0002
#010
print("%8d" %(i0002))
print("%8d" %(i0002))
print("%8d" %(i0002+1))
#011
i0002 = -1
#012
i0001 = 1-i0002
#013
i0001 = i0002-i0001
#014
i0001 = -(i0001+i0002)*(i0001+i0002)
#015
d0001 = -1
#016
d0002 = -d0001/d0002/d0002
#017
i0001 = -(i0001+i0002)
#018
d0001 = -float(i0001)/float(i0002)
#019
i0001 = -i0001/i0002
#020
d0001 = 2.0E0*i0001
#021
i0001 = 2*i0001
#022
d0001 = 7.45E-1
d0002 = math.sin(-(d0001+d0002)/d0001)
d0002 = math.cos(d0001)
d0002 = math.tan(d0001)
d0002 = math.exp(d0001)
d0002 = math.log(d0001)
d0002 = math.log10(d0001)
d0002 = math.sqrt(d0001)
d0002 = math.asin(d0001)
d0002 = math.acos(d0001)
d0002 = math.atan(d0001)
d0002 = math.atan2(d0001,d0002)
d0002 = math.floor(d0001)
d0002 = math.ceil(d0001)
#%%%end testA%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#%%%testB%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
d1001_size[0] = 10
d1001 = numpy.zeros(d1001_size[0])
d1002_size[0] = 10
d1002 = numpy.zeros(d1002_size[0])
d1003_size[0] = 10
d1003 = numpy.zeros(d1003_size[0])
#021
for i0001 in range(0, d1003_size[0], 1):
  d1003[i0001] = d1001[i0001]+d1002[i0001]
#022
for i0001 in range(0, 3, 1):
  d1003[i0001+1] = d1001[i0001+4]+d1002[i0001+4]
#023
for i0001 in range(0, d1003_size[0], 1):
  d1003[i0001] = d1001[i0001]*(d1001[i0001]+d1002[i0001])
d1003_size[0] = -1
del d1003
d2001_size[0] = 10
d2001_size[1] = 5
d2001 = numpy.zeros(d2001_size[0]*d2001_size[1]).reshape(int(d2001_size[0]),int(d2001_size[1]))
d2002_size[0] = 10
d2002_size[1] = 5
d2002 = numpy.zeros(d2002_size[0]*d2002_size[1]).reshape(int(d2002_size[0]),int(d2002_size[1]))
d2003_size[0] = 10
d2003_size[1] = 5
d2003 = numpy.zeros(d2003_size[0]*d2003_size[1]).reshape(int(d2003_size[0]),int(d2003_size[1]))
#024
for i0001 in range(0, d2003_size[0], 1):
  for i0002 in range(0, d2003_size[1], 1):
    d2003[i0001,i0002] = d2001[i0001,i0002]+d2002[i0001,i0002]
#025
for i0001 in range(0, 3, 1):
  d2003[i0001+1,3] = d2001[i0001+4,3]+d2002[i0001+4,3]
#026
for i0001 in range(0, d2003_size[0], 1):
  for i0002 in range(0, d2003_size[1], 1):
    d2003[i0001,i0002] = d2001[i0001,i0002]*(d2001[i0001,i0002]+d2002[i0001,i0002])
d2003_size[0] = -1
d2003_size[1] = -1
del d2003
#027
i0001 = 1
#028
i0001 = 1
i0002 = 1
i0002 = 8*i0001
#aaa
d0001 = 2.0E0*i0001
#bbb
i0002 = 2*i0001
#ccc
d2002_size[0] = -1
d2002_size[1] = -1
del d2002
d2001_size[0] = -1
d2001_size[1] = -1
del d2001
d1002_size[0] = -1
del d1002
d1001_size[0] = -1
del d1001
#%%%end testB%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#%%%testC%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#001
i0001 = 2*i0001
#002
i0001 = 0
#003
d0001 = 1
#004
i0001 = 1
#005
d0001 = 2*(i0001+d0001)
#006
d0001 = 4*i0001
#007
d0001 = 0
#008
d0001 = 0
#009
d0001 = 1
#010
d0001 = 1
#011
d0001 = 1
#%%%end testC%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#%%%testD%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#001
print("001")
d0001 = 1
d0002 = math.sin(d0001)
print("%27.12e" %(d0002))
d0002 = math.cos(d0001)
print("%27.12e" %(d0002))
d0002 = math.tan(d0001)
print("%27.12e" %(d0002))
d0002 = math.exp(d0001)
print("%27.12e" %(d0002))
d0002 = math.log(d0001)
print("%27.12e" %(d0002))
d0002 = math.log10(d0001)
print("%27.12e" %(d0002))
d0002 = math.sqrt(d0001)
print("%27.12e" %(d0002))
d0002 = math.asin(d0001)
print("%27.12e" %(d0002))
d0002 = math.acos(d0001)
print("%27.12e" %(d0002))
d0002 = math.atan(d0001)
print("%27.12e" %(d0002))
d0002 = math.atan2(d0001,d0002)
print("%27.12e" %(d0002))
#002
print("002")
d0001 = 2.8E-1
d0003 = math.sin(d0001)
print("%27.12e" %(d0003))
d0003 = math.cos(d0001)
print("%27.12e" %(d0003))
d0003 = math.tan(d0001)
print("%27.12e" %(d0003))
d0003 = math.exp(d0001)
print("%27.12e" %(d0003))
d0003 = math.log(d0001)
print("%27.12e" %(d0003))
d0003 = math.log10(d0001)
print("%27.12e" %(d0003))
d0003 = math.sqrt(d0001)
print("%27.12e" %(d0003))
d0003 = math.asin(d0001)
print("%27.12e" %(d0003))
d0003 = math.acos(d0001)
print("%27.12e" %(d0003))
d0003 = math.atan(d0001)
print("%27.12e" %(d0003))
d0003 = math.atan2(d0001,d0002)
print("%27.12e" %(d0003))
d0003 = math.floor(d0001)
print("%27.12e" %(d0003))
d0003 = math.ceil(d0001)
print("%27.12e" %(d0003))
#003
print("003")
z0001 = 1.0E0-1.0j*2.0E0
z0002 = cmath.sin(z0001)
print("%27.12e%27.12e" %((z0002).real,(z0002).imag))
z0002 = cmath.cos(z0001)
print("%27.12e%27.12e" %((z0002).real,(z0002).imag))
z0002 = cmath.tan(z0001)
print("%27.12e%27.12e" %((z0002).real,(z0002).imag))
z0002 = cmath.exp(z0001)
print("%27.12e%27.12e" %((z0002).real,(z0002).imag))
z0002 = cmath.log(z0001)
print("%27.12e%27.12e" %((z0002).real,(z0002).imag))
z0002 = cmath.sqrt(z0001)
print("%27.12e%27.12e" %((z0002).real,(z0002).imag))
z0002 = cmath.asin(z0001)
print("%27.12e%27.12e" %((z0002).real,(z0002).imag))
z0002 = cmath.acos(z0001)
print("%27.12e%27.12e" %((z0002).real,(z0002).imag))
z0002 = cmath.atan(z0001)
print("%27.12e%27.12e" %((z0002).real,(z0002).imag))
#%%%end testD%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
