!=============================================================================================
! Project name: test10C
! Project version: aaa
!---------------------------------------------------------------------------------------------
! Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)
! Aqualis version: 1.0.0
! Generated date: 2026/01/04 17:52:15
!=============================================================================================
program test10C
implicit none
character(100) :: t0002
integer :: f0001=12
integer :: tab=2313
integer(1) :: byte_tmp
character(100) :: t0001
integer :: f0000=11
integer :: i0001
double precision :: d0001
double precision :: d0002
double precision :: d0003
write(t0001,"(A)") "data1.dat"
do i0001 = 1, len_trim(t0001)
  if ( t0001( i0001:i0001 ).EQ." " ) t0001( i0001:i0001 ) = "0"
end do
open(f0000, file=trim(t0001))
do i0001=0,20
  d0001 = i0001
  d0002 = 2*i0001+1
  d0003 = 5.0d-1*i0001*i0001
  write(f0000,"(E27.12e3,A1,E27.12e3,A1,E27.12e3)") d0001,tab,d0002,tab,d0003
end do
close(f0000)
write(t0002,"(A)") "data2.dat"
do i0001 = 1, len_trim(t0002)
  if ( t0002( i0001:i0001 ).EQ." " ) t0002( i0001:i0001 ) = "0"
end do
open(f0001, file=trim(t0002))
do i0001=0,20
  d0001 = i0001
  d0002 = 1-2*(i0001-10)
  d0003 = 5.0d-1*(i0001-10)*(i0001-10)
  write(f0001,"(E27.12e3,A1,E27.12e3,A1,E27.12e3)") d0001,tab,d0002,tab,d0003
end do
close(f0001)
contains
end program test10C
