#=============================================================================================
# Project name: test10A
# Project version: aaa
#---------------------------------------------------------------------------------------------
# Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)
# Aqualis version: 1.0.0
# Generated date: 2026/01/04 17:26:51
#=============================================================================================
import numpy
import math
import cmath
import copy
import struct
import re
from scipy.linalg import solve, svd, eig, lu
from scipy.special import jv, yn
import sys
pi = 3.14159265358979
byte_tmp = 0
t0001 = 0
f0000 = 0
i0001 = 0
i0002 = 0
i0003 = 0
z1001 = numpy.array([])
z1001_size = numpy.array([-1])
t0001= "ichimatsuA.svg"%()
f0000 = open(t0001,mode="w")
f0000.write("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" %())
f0000.write("<svg version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" x=\"0px\" y=\"0px\" viewBox=\"0 0 400.000 400.000\" style=\"enable-background:new 0 0 400.000 400.000;\" xml:space=\"preserve\">\n" %())
z1001_size[0] = 4
z1001 = numpy.zeros(z1001_size[0], dtype=numpy.complex128)
for i0001 in range(0, z1001_size[0], 1):
  z1001[i0001] = 2.0E1*cmath.exp((45+90*(i0001-1))*1.0j*pi/1.8E2)
for i0001 in range(-10, 11, 1):
  for i0002 in range(-10, 11, 1):
    for i0003 in range(0, z1001_size[0]-1, 1):
      f0000.write("<path \n" %())
      f0000.write("d=\"M \t%27.12e\t,\t%27.12e\t L \t%27.12e\t,\t%27.12e\t\"\n" %(2.0E2+(i0001*(z1001[0]+z1001[3])+i0002*(z1001[0]+z1001[1])+z1001[i0003]).real,2.0E2-(i0001*(z1001[0]+z1001[3])+i0002*(z1001[0]+z1001[1])+z1001[i0003]).imag,2.0E2+(i0001*(z1001[0]+z1001[3])+i0002*(z1001[0]+z1001[1])+z1001[i0003+1]).real,2.0E2-(i0001*(z1001[0]+z1001[3])+i0002*(z1001[0]+z1001[1])+z1001[i0003+1]).imag))
      f0000.write("style=\"\tstroke:rgb(\t%8d\t,\t%8d\t,\t%8d\t);stroke-opacity:\t%27.12e\t;stroke-width:\t%27.12e\t\t;\t\"\n" %(0,0,0,1.0E0,1.0E0))
      f0000.write("/>\n" %())
    f0000.write("<path \n" %())
    f0000.write("d=\"M \t%27.12e\t,\t%27.12e\t L \t%27.12e\t,\t%27.12e\t\"\n" %(2.0E2+(i0001*(z1001[0]+z1001[3])+i0002*(z1001[0]+z1001[1])+z1001[z1001_size[0]-1]).real,2.0E2-(i0001*(z1001[0]+z1001[3])+i0002*(z1001[0]+z1001[1])+z1001[z1001_size[0]-1]).imag,2.0E2+(i0001*(z1001[0]+z1001[3])+i0002*(z1001[0]+z1001[1])+z1001[0]).real,2.0E2-(i0001*(z1001[0]+z1001[3])+i0002*(z1001[0]+z1001[1])+z1001[0]).imag))
    f0000.write("style=\"\tstroke:rgb(\t%8d\t,\t%8d\t,\t%8d\t);stroke-opacity:\t%27.12e\t;stroke-width:\t%27.12e\t\t;\t\"\n" %(0,0,0,1.0E0,1.0E0))
    f0000.write("/>\n" %())
z1001_size[0] = -1
del z1001
f0000.write("</svg>\n" %())
f0000.close()
