!=============================================================================================
! Project name: test10A
! Project version: aaa
!---------------------------------------------------------------------------------------------
! Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)
! Aqualis version: 1.0.0
! Generated date: 2026/01/04 17:26:51
!=============================================================================================
program test10A
implicit none
double precision :: pi=3.14159265358979d0
complex(kind(0d0)) :: uj=(0d0,1d0)
integer :: tab=2313
integer(1) :: byte_tmp
character(100) :: t0001
integer :: f0000=11
integer :: i0001
integer :: i0002
integer :: i0003
complex(kind(0d0)),allocatable :: z1001(:)
integer :: z1001_size(1:1) = (/ -1 /)
write(t0001,"(A)") "ichimatsuA.svg"
do i0001 = 1, len_trim(t0001)
  if ( t0001( i0001:i0001 ).EQ." " ) t0001( i0001:i0001 ) = "0"
end do
open(f0000, file=trim(t0001))
write(f0000,"(A)") "<?xml version=""1.0"" encoding=""utf-8""?>"
write(f0000,"(A)") "<svg version=""1.1"" xmlns=""http://www.w3.org/2000/svg"" xmlns:xlink=""http://www.w3.org/1999/xlink"" x=""0px"" y=""0px"" viewBox=""0 0 400.000 400.000"" style=""enable-background:new 0 0 400.000 400.000;"" xml:space=""preserve"">"
z1001_size(1) = 4
allocate(z1001(1:z1001_size(1)))
do i0001=0,z1001_size(1)-1
  z1001(i0001+1) = 2.0d1*exp((45+90*(i0001-1))*uj*pi/1.8d2)
end do
do i0001=-10,10
  do i0002=-10,10
    do i0003=0,z1001_size(1)-2
      write(f0000,"(A)") "<path "
      write(f0000,"(A,F0.3,A,F0.3,A,F0.3,A,F0.3,A)") "d=""M ",2.0d2+real(i0001*(z1001(1)+z1001(4))+i0002*(z1001(1)+z1001(2))+z1001(i0003+1)),",",2.0d2-aimag(i0001*(z1001(1)+z1001(4))+i0002*(z1001(1)+z1001(2))+z1001(i0003+1))," L ",2.0d2+real(i0001*(z1001(1)+z1001(4))+i0002*(z1001(1)+z1001(2))+z1001(2+i0003)),",",2.0d2-aimag(i0001*(z1001(1)+z1001(4))+i0002*(z1001(1)+z1001(2))+z1001(2+i0003)),""""
      write(f0000,"(A,A,I0,A,I0,A,I0,A,F0.3,A,F0.3,A,A,A)") "style=""","stroke:rgb(",0,",",0,",",0,");stroke-opacity:",1.0d0,";stroke-width:",1.0d0,"",";",""""
      write(f0000,"(A)") "/>"
    end do
    write(f0000,"(A)") "<path "
    write(f0000,"(A,F0.3,A,F0.3,A,F0.3,A,F0.3,A)") "d=""M ",2.0d2+real(i0001*(z1001(1)+z1001(4))+i0002*(z1001(1)+z1001(2))+z1001(z1001_size(1))),",",2.0d2-aimag(i0001*(z1001(1)+z1001(4))+i0002*(z1001(1)+z1001(2))+z1001(z1001_size(1)))," L ",2.0d2+real(i0001*(z1001(1)+z1001(4))+i0002*(z1001(1)+z1001(2))+z1001(1)),",",2.0d2-aimag(i0001*(z1001(1)+z1001(4))+i0002*(z1001(1)+z1001(2))+z1001(1)),""""
    write(f0000,"(A,A,I0,A,I0,A,I0,A,F0.3,A,F0.3,A,A,A)") "style=""","stroke:rgb(",0,",",0,",",0,");stroke-opacity:",1.0d0,";stroke-width:",1.0d0,"",";",""""
    write(f0000,"(A)") "/>"
  end do
end do
z1001_size(1) = -1
deallocate(z1001)
write(f0000,"(A)") "</svg>"
close(f0000)
contains
end program test10A
