/*=============================================================================================*/
/* Project name: test10A */
/* Project version: aaa */
/*---------------------------------------------------------------------------------------------*/
/* Generated by Aqualis (algorithm and equation analyzer for lightwave simulation) */
/* Aqualis version: 1.0.0 */
/* Generated date: 2026/01/04 17:26:51 */
/*=============================================================================================*/
#include <stdio.h>
#include <stdlib.h>
#include <complex.h>
#include <math.h>
#undef I
#define uj _Complex_I
double pi = 3.14159265358979;
char byte_tmp;
char t0001[100];
FILE* f0000;
int i0001;
int i0002;
int i0003;
double complex *z1001;
int z1001_size[1] = { -1 };
int main()
{
  sprintf(t0001,"ichimatsuA.svg");
  f0000 = fopen(t0001,"w");
  fprintf(f0000,"<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
  fprintf(f0000,"<svg version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" x=\"0px\" y=\"0px\" viewBox=\"0 0 400.000 400.000\" style=\"enable-background:new 0 0 400.000 400.000;\" xml:space=\"preserve\">\n");
  z1001_size[0] = 4;
  z1001 = (double complex *)malloc(sizeof(double complex)*z1001_size[0]);
  for(i0001=0; i0001<=z1001_size[0]-1; i0001++)
  {
    z1001[i0001] = 2.0E1*cexp((45+90*(i0001-1))*uj*pi/1.8E2);
  }
  for(i0001=-10; i0001<=10; i0001++)
  {
    for(i0002=-10; i0002<=10; i0002++)
    {
      for(i0003=0; i0003<=z1001_size[0]-2; i0003++)
      {
        fprintf(f0000,"<path \n");
        fprintf(f0000,"d=\"M %27.12e,%27.12e L %27.12e,%27.12e\"\n",2.0E2+creal(i0001*(z1001[0]+z1001[3])+i0002*(z1001[0]+z1001[1])+z1001[i0003]),2.0E2-cimag(i0001*(z1001[0]+z1001[3])+i0002*(z1001[0]+z1001[1])+z1001[i0003]),2.0E2+creal(i0001*(z1001[0]+z1001[3])+i0002*(z1001[0]+z1001[1])+z1001[i0003+1]),2.0E2-cimag(i0001*(z1001[0]+z1001[3])+i0002*(z1001[0]+z1001[1])+z1001[i0003+1]));
        fprintf(f0000,"style=\"stroke:rgb(%8d,%8d,%8d);stroke-opacity:%27.12e;stroke-width:%27.12e;\"\n",0,0,0,1.0E0,1.0E0);
        fprintf(f0000,"/>\n");
      }
      fprintf(f0000,"<path \n");
      fprintf(f0000,"d=\"M %27.12e,%27.12e L %27.12e,%27.12e\"\n",2.0E2+creal(i0001*(z1001[0]+z1001[3])+i0002*(z1001[0]+z1001[1])+z1001[z1001_size[0]-1]),2.0E2-cimag(i0001*(z1001[0]+z1001[3])+i0002*(z1001[0]+z1001[1])+z1001[z1001_size[0]-1]),2.0E2+creal(i0001*(z1001[0]+z1001[3])+i0002*(z1001[0]+z1001[1])+z1001[0]),2.0E2-cimag(i0001*(z1001[0]+z1001[3])+i0002*(z1001[0]+z1001[1])+z1001[0]));
      fprintf(f0000,"style=\"stroke:rgb(%8d,%8d,%8d);stroke-opacity:%27.12e;stroke-width:%27.12e;\"\n",0,0,0,1.0E0,1.0E0);
      fprintf(f0000,"/>\n");
    }
  }
  z1001_size[0] = -1;
  free(z1001);
  fprintf(f0000,"</svg>\n");
  fclose(f0000);
  return 0;
}
