#=============================================================================================
# Project name: test5tr
# Project version: aaa
#---------------------------------------------------------------------------------------------
# Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)
# Aqualis version: aaa
# Generated date: 2026/01/04 12:23:39
#=============================================================================================
import numpy
import math
import cmath
import copy
import struct
import re
from scipy.linalg import solve, svd, eig, lu
from scipy.special import jv, yn
import sys
byte_tmp = 0
t0001 = 0
f0000 = 0
i0001 = 0
i0002 = 0
i0003 = 0
i0004 = 0
i0005 = 0
i0006 = 0
i0007 = 0
d0001 = 0
d0002 = 0
d0003 = 0
d0004 = 0
d0005 = 0
z0001 = 0
z0002 = 0
i0001 = 1
i0002 = 2
d0001 = 1.234E0
z0001 = 5.6E0+1.0j*7.8E0
t0001= "testA%08d_%08d.dat"%(i0001,i0002)
f0000 = open(t0001,mode="r")
lines = f0000.readline()
word_list = re.split(r'[\t\n]', lines)
i0004 = int(word_list[0])
i0005 = int(word_list[1])
i0006 = int(word_list[2])
print("%8d%8d" %(i0004,i0001))
print("%8d%8d" %(i0005,i0001+1))
print("%8d%8d" %(i0006,i0001+2))
lines = f0000.readline()
word_list = re.split(r'[\t\n]', lines)
i0004 = int(word_list[0])
i0005 = int(word_list[1])
i0006 = int(word_list[2])
print("%8d%8d" %(i0004,i0001+3))
print("%8d%8d" %(i0005,i0001+4))
print("%8d%8d" %(i0006,i0001+5))
lines = f0000.readline()
word_list = re.split(r'[\t\n]', lines)
d0002= float(word_list[0])
z0002 = complex(float(word_list[1]),float(word_list[2]))
print("%27.12e%27.12e" %(d0001,d0002))
print("%27.12e%27.12e%27.12e%27.12e" %((z0001).real,(z0001).imag,(z0002).real,(z0002).imag))
lines = f0000.readline()
word_list = re.split(r'[\t\n]', lines)
d0002= float(word_list[0])
z0002 = complex(float(word_list[1]),float(word_list[2]))
print("%27.12e%27.12e" %(math.sin(d0001),d0002))
print("%27.12e%27.12e%27.12e%27.12e" %((cmath.exp(z0001)).real,(cmath.exp(z0001)).imag,(z0002).real,(z0002).imag))
lines = f0000.readline()
word_list = re.split(r'[\t\n]', lines)
d0002= float(word_list[0])
print("%27.12e%27.12e" %(d0001+math.cos(d0001),d0002))
lines = f0000.readline()
word_list = re.split(r'[\t\n]', lines)
d0002= float(word_list[0])
d0003= float(word_list[1])
print("%27.12e%27.12e" %(abs(z0001),d0002))
print("%27.12e%27.12e" %(abs(z0001)**2,d0003))
f0000.close()
