!=============================================================================================
! Project name: test5tw
! Project version: aaa
!---------------------------------------------------------------------------------------------
! Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)
! Aqualis version: 188.0.0.0
! Generated date: 2026/08/09 19:56:06
!=============================================================================================
program test5tw
use, intrinsic :: ieee_arithmetic
implicit none
integer :: tab=2313
integer(1) :: byte_tmp
character(100) :: t0001
integer :: f0000=11
integer :: i0001
integer :: i0002
integer :: i0003
double precision :: d0001
complex(kind(0d0)) :: z0001
i0001 = 1
i0002 = 2
d0001 = 1.234d0
z0001 = 5.6d0+uj*7.8d0
write(t0001,"(A,I12,A,I12,A)") "testA",i0001,"_",i0002,".dat"
do i0003 = 1, len_trim(t0001)
  if ( t0001( i0003:i0003 ).EQ." " ) t0001( i0003:i0003 ) = "0"
end do
open(f0000, file=trim(t0001))
write(f0000,"(I12,A1,I12,A1,I12)") i0001,tab,i0001+1,tab,i0001+2
write(f0000,"(I12,A1,I12,A1,I12)") i0001+3,tab,i0001+4,tab,i0001+5
write(f0000,"(E27.17e3,A1,E27.17e3,A1,E27.17e3)") d0001,tab,real(z0001),tab,aimag(z0001)
write(f0000,"(E27.17e3,A1,E27.17e3,A1,E27.17e3)") sin(d0001),tab,real(exp(z0001)),tab,aimag(exp(z0001))
write(f0000,"(E27.17e3,A1,E27.17e3)") d0001,tab,cos(d0001)
write(f0000,"(E27.17e3,A1,E27.17e3)") abs(z0001),tab,abs(z0001)**2
close(f0000)
contains
end program test5tw
