#=============================================================================================
# Project name: test5br
# Project version: aaa
#---------------------------------------------------------------------------------------------
# Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)
# Aqualis version: aaa
# Generated date: 2025/12/28 15:07:53
#=============================================================================================
import numpy
import math
import cmath
import copy
import struct
import re
from scipy.linalg import solve, svd, eig, lu
from scipy.special import jv, yn
import sys
byte_tmp = 0
t0001 = 0
f0000 = 0
i0001 = 0
i0002 = 0
i0003 = 0
i0004 = 0
i0005 = 0
i0006 = 0
i0007 = 0
d0001 = 0
d0002 = 0
d0003 = 0
d0004 = 0
d0005 = 0
z0001 = 0
z0002 = 0
i0001 = 1
i0002 = 2
d0001 = 1.234E0
z0001 = 5.6E0+1.0j*7.8E0
t0001= "testA%08d_%08d.bin"%(i0001,i0002)
f0000 = open(t0001,mode="rb")
i0004 = struct.unpack('i', f0000.read(4))[0]
i0005 = struct.unpack('i', f0000.read(4))[0]
i0006 = struct.unpack('i', f0000.read(4))[0]
print("%8d%8d" %(i0004,i0001))
print("%8d%8d" %(i0005,i0001+1))
print("%8d%8d" %(i0006,i0001+2))
i0004 = struct.unpack('i', f0000.read(4))[0]
i0005 = struct.unpack('i', f0000.read(4))[0]
i0006 = struct.unpack('i', f0000.read(4))[0]
print("%8d%8d" %(i0004,i0001+3))
print("%8d%8d" %(i0005,i0001+4))
print("%8d%8d" %(i0006,i0001+5))
d0002 = struct.unpack('d', f0000.read(8))[0]
d0004 = struct.unpack('d', f0000.read(8))[0]
d0005 = struct.unpack('d', f0000.read(8))[0]
z0002 = d0004+1.0j*d0005
print("%27.12e%27.12e" %(d0001,d0002))
print("%27.12e%27.12e%27.12e%27.12e" %((z0001).real,(z0001).imag,(z0002).real,(z0002).imag))
d0002 = struct.unpack('d', f0000.read(8))[0]
d0004 = struct.unpack('d', f0000.read(8))[0]
d0005 = struct.unpack('d', f0000.read(8))[0]
z0002 = d0004+1.0j*d0005
print("%27.12e%27.12e" %(math.sin(d0001),d0002))
print("%27.12e%27.12e%27.12e%27.12e" %((cmath.exp(z0001)).real,(cmath.exp(z0001)).imag,(z0002).real,(z0002).imag))
d0002 = struct.unpack('d', f0000.read(8))[0]
print("%27.12e%27.12e" %(d0001+math.cos(d0001),d0002))
d0002 = struct.unpack('d', f0000.read(8))[0]
d0003 = struct.unpack('d', f0000.read(8))[0]
print("%27.12e%27.12e" %(abs(z0001),d0002))
print("%27.12e%27.12e" %(abs(z0001)**2,d0003))
f0000.close()
