#=============================================================================================
# Project name: test5tw
# Project version: aaa
#---------------------------------------------------------------------------------------------
# Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)
# Aqualis version: aaa
# Generated date: 2025/12/28 15:07:53
#=============================================================================================
import numpy
import math
import cmath
import copy
import struct
import re
from scipy.linalg import solve, svd, eig, lu
from scipy.special import jv, yn
import sys
byte_tmp = 0
t0001 = 0
f0000 = 0
i0001 = 0
i0002 = 0
d0001 = 0
z0001 = 0
i0001 = 1
i0002 = 2
d0001 = 1.234E0
z0001 = 5.6E0+1.0j*7.8E0
t0001= "testA%08d_%08d.dat"%(i0001,i0002)
f0000 = open(t0001,mode="w")
f0000.write("%8d\t%8d\t%8d\n" %(i0001,i0001+1,i0001+2))
f0000.write("%8d\t%8d\t%8d\n" %(i0001+3,i0001+4,i0001+5))
f0000.write("%27.12e\t%27.12e\t%27.12e\n" %(d0001,(z0001).real,(z0001).imag))
f0000.write("%27.12e\t%27.12e\t%27.12e\n" %(math.sin(d0001),(cmath.exp(z0001)).real,(cmath.exp(z0001)).imag))
f0000.write("%27.12e\n" %(d0001+math.cos(d0001)))
f0000.write("%27.12e\t%27.12e\n" %(abs(z0001),abs(z0001)**2))
f0000.close()
