!=============================================================================================
! Project name: test5br
! Project version: aaa
!---------------------------------------------------------------------------------------------
! Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)
! Aqualis version: aaa
! Generated date: 2025/12/28 15:07:53
!=============================================================================================
program test5br
implicit none
integer(1) :: byte_tmp
character(100) :: t0001
integer :: f0000=11
complex(kind(0d0)) :: uj=(0d0,1d0)
integer :: i0001
integer :: i0002
integer :: i0003
integer :: i0004
integer :: i0005
integer :: i0006
integer :: i0007
double precision :: d0001
double precision :: d0002
double precision :: d0003
double precision :: d0004
double precision :: d0005
complex(kind(0d0)) :: z0001
complex(kind(0d0)) :: z0002
i0001 = 1
i0002 = 2
d0001 = 1.234d0
z0001 = 5.6d0+uj*7.8d0
write(t0001,"(A,I8,A,I8,A)") "testA",i0001,"_",i0002,".bin"
do i0004 = 1, len_trim(t0001)
  if ( t0001( i0004:i0004 ).EQ." " ) t0001( i0004:i0004 ) = "0"
end do
open(f0000, file=trim(t0001), access='stream', form='unformatted')
read(f0000,iostat=i0003) i0004
read(f0000,iostat=i0003) i0005
read(f0000,iostat=i0003) i0006
print *, i0004,i0001
print *, i0005,i0001+1
print *, i0006,i0001+2
read(f0000,iostat=i0003) i0004
read(f0000,iostat=i0003) i0005
read(f0000,iostat=i0003) i0006
print *, i0004,i0001+3
print *, i0005,i0001+4
print *, i0006,i0001+5
read(f0000,iostat=i0003) d0002
read(f0000,iostat=i0003) d0004
read(f0000,iostat=i0003) d0005
z0002 = d0004+uj*d0005
print *, d0001,d0002
print *, real(z0001),aimag(z0001),real(z0002),aimag(z0002)
read(f0000,iostat=i0003) d0002
read(f0000,iostat=i0003) d0004
read(f0000,iostat=i0003) d0005
z0002 = d0004+uj*d0005
print *, sin(d0001),d0002
print *, real(exp(z0001)),aimag(exp(z0001)),real(z0002),aimag(z0002)
read(f0000,iostat=i0003) d0002
print *, d0001+cos(d0001),d0002
read(f0000,iostat=i0003) d0002
read(f0000,iostat=i0003) d0003
print *, abs(z0001),d0002
print *, abs(z0001)**2,d0003
close(f0000)
contains
end program test5br
