/*=============================================================================================*/
/* Project name: test5br */
/* Project version: aaa */
/*---------------------------------------------------------------------------------------------*/
/* Generated by Aqualis (algorithm and equation analyzer for lightwave simulation) */
/* Aqualis version: aaa */
/* Generated date: 2026/01/04 12:23:39 */
/*=============================================================================================*/
#include <stdio.h>
#include <stdlib.h>
#include <complex.h>
#include <math.h>
#undef I
#define uj _Complex_I
char byte_tmp;
char t0001[100];
FILE* f0000;
int i0001;
int i0002;
int i0003;
int i0004;
int i0005;
int i0006;
int i0007;
double d0001;
double d0002;
double d0003;
double d0004;
double d0005;
double complex z0001;
double complex z0002;
int main()
{
  i0001 = 1;
  i0002 = 2;
  d0001 = 1.234E0;
  z0001 = 5.6E0+uj*7.8E0;
  sprintf(t0001,"testA%08d_%08d.bin",i0001,i0002);
  f0000 = fopen(t0001,"rb");
  fread(&i0004,sizeof(i0004),1,f0000);
  fread(&i0005,sizeof(i0005),1,f0000);
  fread(&i0006,sizeof(i0006),1,f0000);
  printf("%8d%8d\n",i0004,i0001);
  printf("%8d%8d\n",i0005,i0001+1);
  printf("%8d%8d\n",i0006,i0001+2);
  fread(&i0004,sizeof(i0004),1,f0000);
  fread(&i0005,sizeof(i0005),1,f0000);
  fread(&i0006,sizeof(i0006),1,f0000);
  printf("%8d%8d\n",i0004,i0001+3);
  printf("%8d%8d\n",i0005,i0001+4);
  printf("%8d%8d\n",i0006,i0001+5);
  fread(&d0002,sizeof(d0002),1,f0000);
  fread(&d0004,sizeof(d0004),1,f0000);
  fread(&d0005,sizeof(d0005),1,f0000);
  z0002 = d0004+uj*d0005;
  printf("%27.12e%27.12e\n",d0001,d0002);
  printf("%27.12e%27.12e%27.12e%27.12e\n",creal(z0001),cimag(z0001),creal(z0002),cimag(z0002));
  fread(&d0002,sizeof(d0002),1,f0000);
  fread(&d0004,sizeof(d0004),1,f0000);
  fread(&d0005,sizeof(d0005),1,f0000);
  z0002 = d0004+uj*d0005;
  printf("%27.12e%27.12e\n",sin(d0001),d0002);
  printf("%27.12e%27.12e%27.12e%27.12e\n",creal(cexp(z0001)),cimag(cexp(z0001)),creal(z0002),cimag(z0002));
  fread(&d0002,sizeof(d0002),1,f0000);
  printf("%27.12e%27.12e\n",d0001+cos(d0001),d0002);
  fread(&d0002,sizeof(d0002),1,f0000);
  fread(&d0003,sizeof(d0003),1,f0000);
  printf("%27.12e%27.12e\n",cabs(z0001),d0002);
  printf("%27.12e%27.12e\n",pow(cabs(z0001),2),d0003);
  fclose(f0000);
  return 0;
}
