!=============================================================================================
! Project name: test5bw
! Project version: aaa
!---------------------------------------------------------------------------------------------
! Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)
! Aqualis version: aaa
! Generated date: 2026/01/04 12:23:39
!=============================================================================================
program test5bw
implicit none
integer(1) :: byte_tmp
character(100) :: t0001
integer :: f0000=11
complex(kind(0d0)) :: uj=(0d0,1d0)
integer :: i0001
integer :: i0002
integer :: i0003
double precision :: d0001
complex(kind(0d0)) :: z0001
i0001 = 1
i0002 = 2
d0001 = 1.234d0
z0001 = 5.6d0+uj*7.8d0
write(t0001,"(A,I8,A,I8,A)") "testA",i0001,"_",i0002,".bin"
do i0003 = 1, len_trim(t0001)
  if ( t0001( i0003:i0003 ).EQ." " ) t0001( i0003:i0003 ) = "0"
end do
open(f0000, file=trim(t0001), access='stream', form='unformatted')
write(f0000) i0001
write(f0000) i0001+1
write(f0000) i0001+2
write(f0000) i0001+3
write(f0000) i0001+4
write(f0000) i0001+5
write(f0000) d0001
write(f0000) real(z0001)
write(f0000) aimag(z0001)
write(f0000) sin(d0001)
write(f0000) real(exp(z0001))
write(f0000) aimag(exp(z0001))
write(f0000) d0001+cos(d0001)
write(f0000) abs(z0001)
write(f0000) abs(z0001)**2
close(f0000)
contains
end program test5bw
