#=============================================================================================
# Project name: test5bw
# Project version: aaa
#---------------------------------------------------------------------------------------------
# Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)
# Aqualis version: aaa
# Generated date: 2026/01/04 12:23:39
#=============================================================================================
import numpy
import math
import cmath
import copy
import struct
import re
from scipy.linalg import solve, svd, eig, lu
from scipy.special import jv, yn
import sys
byte_tmp = 0
t0001 = 0
f0000 = 0
i0001 = 0
i0002 = 0
i0003 = 0
d0001 = 0
d0002 = 0
d0003 = 0
z0001 = 0
i0001 = 1
i0002 = 2
d0001 = 1.234E0
z0001 = 5.6E0+1.0j*7.8E0
t0001= "testA%08d_%08d.bin"%(i0001,i0002)
f0000 = open(t0001,mode="wb")
i0003 = i0001
f0000.write(struct.pack('i', i0003))
i0003 = i0001+1
f0000.write(struct.pack('i', i0003))
i0003 = i0001+2
f0000.write(struct.pack('i', i0003))
i0003 = i0001+3
f0000.write(struct.pack('i', i0003))
i0003 = i0001+4
f0000.write(struct.pack('i', i0003))
i0003 = i0001+5
f0000.write(struct.pack('i', i0003))
d0002 = d0001
f0000.write(struct.pack('d', d0002))
d0002 = (z0001).real
d0003 = (z0001).imag
f0000.write(struct.pack('d', d0002))
f0000.write(struct.pack('d', d0003))
d0002 = math.sin(d0001)
f0000.write(struct.pack('d', d0002))
d0002 = (cmath.exp(z0001)).real
d0003 = (cmath.exp(z0001)).imag
f0000.write(struct.pack('d', d0002))
f0000.write(struct.pack('d', d0003))
d0002 = d0001+math.cos(d0001)
f0000.write(struct.pack('d', d0002))
d0002 = abs(z0001)
f0000.write(struct.pack('d', d0002))
d0002 = abs(z0001)**2
f0000.write(struct.pack('d', d0002))
f0000.close()
