/*=============================================================================================*/
/* Project name: test5bw */
/* Project version: aaa */
/*---------------------------------------------------------------------------------------------*/
/* Generated by Aqualis (algorithm and equation analyzer for lightwave simulation) */
/* Aqualis version: aaa */
/* Generated date: 2026/01/04 12:23:39 */
/*=============================================================================================*/
#include <stdio.h>
#include <stdlib.h>
#include <complex.h>
#include <math.h>
#undef I
#define uj _Complex_I
char byte_tmp;
char t0001[100];
FILE* f0000;
int i0001;
int i0002;
int i0003;
double d0001;
double d0002;
double d0003;
double complex z0001;
int main()
{
  i0001 = 1;
  i0002 = 2;
  d0001 = 1.234E0;
  z0001 = 5.6E0+uj*7.8E0;
  sprintf(t0001,"testA%08d_%08d.bin",i0001,i0002);
  f0000 = fopen(t0001,"wb");
  i0003 = i0001;
  fwrite(&i0003,sizeof(i0003),1,f0000);
  i0003 = i0001+1;
  fwrite(&i0003,sizeof(i0003),1,f0000);
  i0003 = i0001+2;
  fwrite(&i0003,sizeof(i0003),1,f0000);
  i0003 = i0001+3;
  fwrite(&i0003,sizeof(i0003),1,f0000);
  i0003 = i0001+4;
  fwrite(&i0003,sizeof(i0003),1,f0000);
  i0003 = i0001+5;
  fwrite(&i0003,sizeof(i0003),1,f0000);
  d0002 = d0001;
  fwrite(&d0002,sizeof(d0002),1,f0000);
  d0002 = creal(z0001);
  d0003 = cimag(z0001);
  fwrite(&d0002,sizeof(d0002),1,f0000);
  fwrite(&d0003,sizeof(d0003),1,f0000);
  d0002 = sin(d0001);
  fwrite(&d0002,sizeof(d0002),1,f0000);
  d0002 = creal(cexp(z0001));
  d0003 = cimag(cexp(z0001));
  fwrite(&d0002,sizeof(d0002),1,f0000);
  fwrite(&d0003,sizeof(d0003),1,f0000);
  d0002 = d0001+cos(d0001);
  fwrite(&d0002,sizeof(d0002),1,f0000);
  d0002 = cabs(z0001);
  fwrite(&d0002,sizeof(d0002),1,f0000);
  d0002 = pow(cabs(z0001),2);
  fwrite(&d0002,sizeof(d0002),1,f0000);
  fclose(f0000);
  return 0;
}
