/*=============================================================================================*/
/* Project name: test5tw */
/* Project version: aaa */
/*---------------------------------------------------------------------------------------------*/
/* Generated by Aqualis (algorithm and equation analyzer for lightwave simulation) */
/* Aqualis version: aaa */
/* Generated date: 2026/01/04 12:23:39 */
/*=============================================================================================*/
#include <stdio.h>
#include <stdlib.h>
#include <complex.h>
#include <math.h>
#undef I
#define uj _Complex_I
char byte_tmp;
char t0001[100];
FILE* f0000;
int i0001;
int i0002;
double d0001;
double complex z0001;
int main()
{
  i0001 = 1;
  i0002 = 2;
  d0001 = 1.234E0;
  z0001 = 5.6E0+uj*7.8E0;
  sprintf(t0001,"testA%08d_%08d.dat",i0001,i0002);
  f0000 = fopen(t0001,"w");
  fprintf(f0000,"%8d\t%8d\t%8d\n",i0001,i0001+1,i0001+2);
  fprintf(f0000,"%8d\t%8d\t%8d\n",i0001+3,i0001+4,i0001+5);
  fprintf(f0000,"%27.12e\t%27.12e\t%27.12e\n",d0001,creal(z0001),cimag(z0001));
  fprintf(f0000,"%27.12e\t%27.12e\t%27.12e\n",sin(d0001),creal(cexp(z0001)),cimag(cexp(z0001)));
  fprintf(f0000,"%27.12e\n",d0001+cos(d0001));
  fprintf(f0000,"%27.12e\t%27.12e\n",cabs(z0001),pow(cabs(z0001),2));
  fclose(f0000);
  return 0;
}
