!=============================================================================================
! Project name: test6_1
! Project version: 1.0.0
!---------------------------------------------------------------------------------------------
! Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)
! Aqualis version: 188.0.0.0
! Generated date: 2026/09/03 16:30:56
!=============================================================================================
program test6_1
use, intrinsic :: ieee_arithmetic
implicit none
complex(kind(0d0)) :: uj=(0d0,1d0)
integer :: i0001
double precision :: d0001
double precision :: d0002
double precision :: d0003
double precision :: d0004
double precision :: d0005
double precision :: d0006
double precision :: d0007
double precision :: d0008
double precision :: d0009
double precision :: d0010
double precision :: d0011
double precision :: d0012
double precision :: d0013
double precision :: d0014
double precision :: d0015
double precision :: d0016
double precision :: d0017
double precision :: d0018
double precision :: d0019
double precision :: d0020
double precision :: d0021
double precision :: d0022
double precision :: d0023
double precision :: d0024
double precision :: d0025
double precision :: d0026
double precision :: d0027
double precision :: d0028
d0001 = -10
!代数微分
d0006 = d0001**2+1
d0007 = sqrt(2*d0006)
d0008 = sin(d0007-1)
d0009 = sin(d0007-1)
d0010 = sqrt(2*d0006)
d0011 = sin(d0010-1)
d0012 = sin(d0010-1)
d0013 = 0
do i0001=1,10
  d0013 = d0013+2*(d0001/(i0001*d0008)-1)*1/(i0001*d0008)
end do
d0014 = 0
do i0001=1,10
  d0014 = d0014+(d0001/(i0001*d0008)-1)**2
end do
d0015 = 0
do i0001=1,10
  d0015 = d0015
end do
d0016 = 0
do i0001=1,10
  d0016 = d0016+(d0001/(i0001*d0011)-1)**2
end do
d0017 = 0
do i0001=1,10
  d0017 = d0017
end do
d0018 = 0
do i0001=1,10
  d0018 = d0018+(d0001/(i0001*d0012)-1)**2
end do
d0019 = 0
do i0001=1,10
  d0019 = d0019-2*(d0001/(i0001*d0012)-1)*d0001/(i0001*d0012)**2*i0001
end do
d0020 = 0
do i0001=1,10
  d0020 = d0020+(d0001/(i0001*d0012)-1)**2
end do
d0004 = 5.0d-1*d0013/sqrt(d0014)+(5.0d-1*d0015/sqrt(d0016)+(5.0d-1*d0017/sqrt(d0018)+5.0d-1*d0019/sqrt(d0020)*cos(d0010-1))*1.0d0/sqrt(2*d0006))*2*d0001
!数値微分
d0021 = d0001**2+1
d0022 = sqrt(2*d0021)
d0023 = sin(d0022-1)
d0024 = 0
do i0001=1,10
  d0024 = d0024+(d0001/(i0001*d0023)-1)**2
end do
d0002 = sqrt(d0024)
d0001 = d0001+1.0d-5
d0025 = d0001**2+1
d0026 = sqrt(2*d0025)
d0027 = sin(d0026-1)
d0028 = 0
do i0001=1,10
  d0028 = d0028+(d0001/(i0001*d0027)-1)**2
end do
d0003 = sqrt(d0028)
d0001 = d0001-1.0d-5
print *, d0004,(d0003-d0002)/1.0d-5
contains
end program test6_1
