!=============================================================================================
! Project name: test6_2
! Project version: aaa
!---------------------------------------------------------------------------------------------
! Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)
! Aqualis version: aaa
! Generated date: 2026/07/23 14:14:22
!=============================================================================================
program test6_2
use, intrinsic :: ieee_arithmetic
implicit none
include 'fftw3.f'
character(100) :: t0001
integer :: f0000=10
integer :: ftplan3(1:8)
integer :: ftplan3_size(1:1) = (/ 8 /)
integer :: ftplan2(1:8)
integer :: ftplan2_size(1:1) = (/ 8 /)
integer :: ftplan1(1:8)
integer :: ftplan1_size(1:1) = (/ 8 /)
character(100) :: t0001
integer :: f0000=10
integer :: tab=2313
integer(1) :: byte_tmp
character(100) :: t0001
integer :: f0000=11
integer :: i0001
integer :: i0002
integer :: i0003
integer :: i0004
integer :: i0005
integer :: i0006
integer :: i0007
integer :: i0008
complex(kind(0d0)) :: z0001
complex(kind(0d0)),allocatable :: z2001(:,:)
integer :: z2001_size(1:2) = (/ -1,-1 /)
complex(kind(0d0)),allocatable :: z2002(:,:)
integer :: z2002_size(1:2) = (/ -1,-1 /)
z2001_size(1) = 101
z2001_size(2) = 101
allocate(z2001(1:z2001_size(1),1:z2001_size(2)))
z2002_size(1) = 101
z2002_size(2) = 101
allocate(z2002(1:z2002_size(1),1:z2002_size(2)))
z2001=0
z2001(51,51) = 1
write(t0001,"(A)") "f.dat"
do i0001 = 1, len_trim(t0001)
  if ( t0001( i0001:i0001 ).EQ." " ) t0001( i0001:i0001 ) = "0"
end do
open(f0000, file=trim(t0001))
do i0001=0,z2001_size(1)-1
  do i0002=0,z2001_size(2)-1
    write(f0000,"(I12,A1,I12,A1,E27.17e3,A1,E27.17e3)") i0001,tab,i0002,tab,real(z2001(i0001+1,i0002+1)),tab,aimag(z2001(i0001+1,i0002+1))
  end do
end do
close(f0000)
z2002=0
z2002(51,51) = 1
write(t0001,"(A)") "g.dat"
do i0001 = 1, len_trim(t0001)
  if ( t0001( i0001:i0001 ).EQ." " ) t0001( i0001:i0001 ) = "0"
end do
open(f0000, file=trim(t0001))
do i0001=0,z2002_size(1)-1
  do i0002=0,z2002_size(2)-1
    write(f0000,"(I12,A1,I12,A1,E27.17e3,A1,E27.17e3)") i0001,tab,i0002,tab,real(z2002(i0001+1,i0002+1)),tab,aimag(z2002(i0001+1,i0002+1))
  end do
end do
close(f0000)
i0001 = z2001_size(1)
i0002 = z2001_size(2)
i0003 = z2001_size(1)/2
i0004 = z2001_size(2)/2
call dfftw_plan_dft_2d(ftplan1, i0001, i0002, z2001, z2001, FFTW_FORWARD, FFTW_ESTIMATE )
if(mod(z2001_size(2),2) == 0) then
  do i0005=0,z2001_size(1)-1
    do i0006=0,z2001_size(2)/2-1
      z0001 = z2001(i0005+1,i0006+z2001_size(2)/2+1)
      z2001(i0005+1,i0006+z2001_size(2)/2+1) = z2001(i0005+1,i0006+1)
      z2001(i0005+1,i0006+1) = z0001
    end do
  end do
else
  do i0005=0,z2001_size(1)-1
    i0006 = 0
    z0001 = z2001(i0005+1,i0006+1)
    do i0008=0,z2001_size(2)-1
      if(i0006+z2001_size(2)/2+1 >= z2001_size(2)) then
        i0007 = i0006+z2001_size(2)/2+1-z2001_size(2)
      else
        i0007 = i0006+z2001_size(2)/2+1
      endif
      z2001(i0005+1,i0006+1) = z2001(i0005+1,i0007+1)
      i0006 = i0007
    end do
    z2001(i0005+1,i0006+z2001_size(2)/2+1) = z0001
  end do
endif
if(mod(z2001_size(1),2) == 0) then
  do i0005=0,z2001_size(2)-1
    do i0006=0,z2001_size(1)/2-1
      z0001 = z2001(i0006+z2001_size(1)/2+1,i0005+1)
      z2001(i0006+z2001_size(1)/2+1,i0005+1) = z2001(i0006+1,i0005+1)
      z2001(i0006+1,i0005+1) = z0001
    end do
  end do
else
  do i0005=0,z2001_size(2)-1
    i0006 = 0
    z0001 = z2001(i0006+1,i0005+1)
    do i0008=0,z2001_size(1)-1
      if(i0006+z2001_size(1)/2+1 >= z2001_size(1)) then
        i0007 = i0006+z2001_size(1)/2+1-z2001_size(1)
      else
        i0007 = i0006+z2001_size(1)/2+1
      endif
      z2001(i0006+1,i0005+1) = z2001(i0007+1,i0005+1)
      i0006 = i0007
    end do
    z2001(i0006+z2001_size(1)/2+1,i0005+1) = z0001
  end do
endif
!FFT
call dfftw_execute(ftplan1)
if(mod(z2001_size(2),2) == 0) then
  do i0005=0,z2001_size(1)-1
    do i0006=0,z2001_size(2)/2-1
      z0001 = z2001(i0005+1,i0006+z2001_size(2)/2+1)
      z2001(i0005+1,i0006+z2001_size(2)/2+1) = z2001(i0005+1,i0006+1)
      z2001(i0005+1,i0006+1) = z0001
    end do
  end do
else
  do i0005=0,z2001_size(1)-1
    i0006 = 0
    z0001 = z2001(i0005+1,i0006+1)
    do i0008=0,z2001_size(2)-1
      if(i0006+z2001_size(2)/2+1 >= z2001_size(2)) then
        i0007 = i0006+z2001_size(2)/2+1-z2001_size(2)
      else
        i0007 = i0006+z2001_size(2)/2+1
      endif
      z2001(i0005+1,i0006+1) = z2001(i0005+1,i0007+1)
      i0006 = i0007
    end do
    z2001(i0005+1,i0006+z2001_size(2)/2+1) = z0001
  end do
endif
if(mod(z2001_size(1),2) == 0) then
  do i0005=0,z2001_size(2)-1
    do i0006=0,z2001_size(1)/2-1
      z0001 = z2001(i0006+z2001_size(1)/2+1,i0005+1)
      z2001(i0006+z2001_size(1)/2+1,i0005+1) = z2001(i0006+1,i0005+1)
      z2001(i0006+1,i0005+1) = z0001
    end do
  end do
else
  do i0005=0,z2001_size(2)-1
    i0006 = 0
    z0001 = z2001(i0006+1,i0005+1)
    do i0008=0,z2001_size(1)-1
      if(i0006+z2001_size(1)/2+1 >= z2001_size(1)) then
        i0007 = i0006+z2001_size(1)/2+1-z2001_size(1)
      else
        i0007 = i0006+z2001_size(1)/2+1
      endif
      z2001(i0006+1,i0005+1) = z2001(i0007+1,i0005+1)
      i0006 = i0007
    end do
    z2001(i0006+z2001_size(1)/2+1,i0005+1) = z0001
  end do
endif
call dfftw_destroy_plan(ftplan1)
!normalize
do i0005=0,i0001-1
  do i0006=0,i0002-1
    z2001(i0005+1,i0006+1) = z2001(i0005+1,i0006+1)/(i0001*i0002)
  end do
end do
i0001 = z2002_size(1)
i0002 = z2002_size(2)
i0003 = z2002_size(1)/2
i0004 = z2002_size(2)/2
call dfftw_plan_dft_2d(ftplan2, i0001, i0002, z2002, z2002, FFTW_FORWARD, FFTW_ESTIMATE )
if(mod(z2002_size(2),2) == 0) then
  do i0005=0,z2002_size(1)-1
    do i0006=0,z2002_size(2)/2-1
      z0001 = z2002(i0005+1,i0006+z2002_size(2)/2+1)
      z2002(i0005+1,i0006+z2002_size(2)/2+1) = z2002(i0005+1,i0006+1)
      z2002(i0005+1,i0006+1) = z0001
    end do
  end do
else
  do i0005=0,z2002_size(1)-1
    i0006 = 0
    z0001 = z2002(i0005+1,i0006+1)
    do i0008=0,z2002_size(2)-1
      if(i0006+z2002_size(2)/2+1 >= z2002_size(2)) then
        i0007 = i0006+z2002_size(2)/2+1-z2002_size(2)
      else
        i0007 = i0006+z2002_size(2)/2+1
      endif
      z2002(i0005+1,i0006+1) = z2002(i0005+1,i0007+1)
      i0006 = i0007
    end do
    z2002(i0005+1,i0006+z2002_size(2)/2+1) = z0001
  end do
endif
if(mod(z2002_size(1),2) == 0) then
  do i0005=0,z2002_size(2)-1
    do i0006=0,z2002_size(1)/2-1
      z0001 = z2002(i0006+z2002_size(1)/2+1,i0005+1)
      z2002(i0006+z2002_size(1)/2+1,i0005+1) = z2002(i0006+1,i0005+1)
      z2002(i0006+1,i0005+1) = z0001
    end do
  end do
else
  do i0005=0,z2002_size(2)-1
    i0006 = 0
    z0001 = z2002(i0006+1,i0005+1)
    do i0008=0,z2002_size(1)-1
      if(i0006+z2002_size(1)/2+1 >= z2002_size(1)) then
        i0007 = i0006+z2002_size(1)/2+1-z2002_size(1)
      else
        i0007 = i0006+z2002_size(1)/2+1
      endif
      z2002(i0006+1,i0005+1) = z2002(i0007+1,i0005+1)
      i0006 = i0007
    end do
    z2002(i0006+z2002_size(1)/2+1,i0005+1) = z0001
  end do
endif
!FFT
call dfftw_execute(ftplan2)
if(mod(z2002_size(2),2) == 0) then
  do i0005=0,z2002_size(1)-1
    do i0006=0,z2002_size(2)/2-1
      z0001 = z2002(i0005+1,i0006+z2002_size(2)/2+1)
      z2002(i0005+1,i0006+z2002_size(2)/2+1) = z2002(i0005+1,i0006+1)
      z2002(i0005+1,i0006+1) = z0001
    end do
  end do
else
  do i0005=0,z2002_size(1)-1
    i0006 = 0
    z0001 = z2002(i0005+1,i0006+1)
    do i0008=0,z2002_size(2)-1
      if(i0006+z2002_size(2)/2+1 >= z2002_size(2)) then
        i0007 = i0006+z2002_size(2)/2+1-z2002_size(2)
      else
        i0007 = i0006+z2002_size(2)/2+1
      endif
      z2002(i0005+1,i0006+1) = z2002(i0005+1,i0007+1)
      i0006 = i0007
    end do
    z2002(i0005+1,i0006+z2002_size(2)/2+1) = z0001
  end do
endif
if(mod(z2002_size(1),2) == 0) then
  do i0005=0,z2002_size(2)-1
    do i0006=0,z2002_size(1)/2-1
      z0001 = z2002(i0006+z2002_size(1)/2+1,i0005+1)
      z2002(i0006+z2002_size(1)/2+1,i0005+1) = z2002(i0006+1,i0005+1)
      z2002(i0006+1,i0005+1) = z0001
    end do
  end do
else
  do i0005=0,z2002_size(2)-1
    i0006 = 0
    z0001 = z2002(i0006+1,i0005+1)
    do i0008=0,z2002_size(1)-1
      if(i0006+z2002_size(1)/2+1 >= z2002_size(1)) then
        i0007 = i0006+z2002_size(1)/2+1-z2002_size(1)
      else
        i0007 = i0006+z2002_size(1)/2+1
      endif
      z2002(i0006+1,i0005+1) = z2002(i0007+1,i0005+1)
      i0006 = i0007
    end do
    z2002(i0006+z2002_size(1)/2+1,i0005+1) = z0001
  end do
endif
call dfftw_destroy_plan(ftplan2)
!normalize
do i0005=0,i0001-1
  do i0006=0,i0002-1
    z2002(i0005+1,i0006+1) = z2002(i0005+1,i0006+1)/(i0001*i0002)
  end do
end do
do i0001=0,z2001_size(1)-1
  do i0002=0,z2001_size(2)-1
    z2001(i0001+1,i0002+1) = z2001(i0001+1,i0002+1)*conjg(z2002(i0001+1,i0002+1))
  end do
end do
i0001 = z2001_size(1)
i0002 = z2001_size(2)
i0003 = z2001_size(1)/2
i0004 = z2001_size(2)/2
call dfftw_plan_dft_2d(ftplan3, i0001, i0002, z2001, z2001, FFTW_BACKWARD, FFTW_ESTIMATE )
if(mod(z2001_size(2),2) == 0) then
  do i0005=0,z2001_size(1)-1
    do i0006=0,z2001_size(2)/2-1
      z0001 = z2001(i0005+1,i0006+z2001_size(2)/2+1)
      z2001(i0005+1,i0006+z2001_size(2)/2+1) = z2001(i0005+1,i0006+1)
      z2001(i0005+1,i0006+1) = z0001
    end do
  end do
else
  do i0005=0,z2001_size(1)-1
    i0006 = 0
    z0001 = z2001(i0005+1,i0006+1)
    do i0008=0,z2001_size(2)-1
      if(i0006+z2001_size(2)/2 >= z2001_size(2)) then
        i0007 = i0006+z2001_size(2)/2-z2001_size(2)
      else
        i0007 = i0006+z2001_size(2)/2
      endif
      z2001(i0005+1,i0006+1) = z2001(i0005+1,i0007+1)
      i0006 = i0007
    end do
    z2001(i0005+1,2+i0006+z2001_size(2)/2) = z0001
  end do
endif
if(mod(z2001_size(1),2) == 0) then
  do i0005=0,z2001_size(2)-1
    do i0006=0,z2001_size(1)/2-1
      z0001 = z2001(i0006+z2001_size(1)/2+1,i0005+1)
      z2001(i0006+z2001_size(1)/2+1,i0005+1) = z2001(i0006+1,i0005+1)
      z2001(i0006+1,i0005+1) = z0001
    end do
  end do
else
  do i0005=0,z2001_size(2)-1
    i0006 = 0
    z0001 = z2001(i0006+1,i0005+1)
    do i0008=0,z2001_size(1)-1
      if(i0006+z2001_size(1)/2 >= z2001_size(1)) then
        i0007 = i0006+z2001_size(1)/2-z2001_size(1)
      else
        i0007 = i0006+z2001_size(1)/2
      endif
      z2001(i0006+1,i0005+1) = z2001(i0007+1,i0005+1)
      i0006 = i0007
    end do
    z2001(2+i0006+z2001_size(1)/2,i0005+1) = z0001
  end do
endif
!FFT
call dfftw_execute(ftplan3)
if(mod(z2001_size(2),2) == 0) then
  do i0005=0,z2001_size(1)-1
    do i0006=0,z2001_size(2)/2-1
      z0001 = z2001(i0005+1,i0006+z2001_size(2)/2+1)
      z2001(i0005+1,i0006+z2001_size(2)/2+1) = z2001(i0005+1,i0006+1)
      z2001(i0005+1,i0006+1) = z0001
    end do
  end do
else
  do i0005=0,z2001_size(1)-1
    i0006 = 0
    z0001 = z2001(i0005+1,i0006+1)
    do i0008=0,z2001_size(2)-1
      if(i0006+z2001_size(2)/2 >= z2001_size(2)) then
        i0007 = i0006+z2001_size(2)/2-z2001_size(2)
      else
        i0007 = i0006+z2001_size(2)/2
      endif
      z2001(i0005+1,i0006+1) = z2001(i0005+1,i0007+1)
      i0006 = i0007
    end do
    z2001(i0005+1,2+i0006+z2001_size(2)/2) = z0001
  end do
endif
if(mod(z2001_size(1),2) == 0) then
  do i0005=0,z2001_size(2)-1
    do i0006=0,z2001_size(1)/2-1
      z0001 = z2001(i0006+z2001_size(1)/2+1,i0005+1)
      z2001(i0006+z2001_size(1)/2+1,i0005+1) = z2001(i0006+1,i0005+1)
      z2001(i0006+1,i0005+1) = z0001
    end do
  end do
else
  do i0005=0,z2001_size(2)-1
    i0006 = 0
    z0001 = z2001(i0006+1,i0005+1)
    do i0008=0,z2001_size(1)-1
      if(i0006+z2001_size(1)/2 >= z2001_size(1)) then
        i0007 = i0006+z2001_size(1)/2-z2001_size(1)
      else
        i0007 = i0006+z2001_size(1)/2
      endif
      z2001(i0006+1,i0005+1) = z2001(i0007+1,i0005+1)
      i0006 = i0007
    end do
    z2001(2+i0006+z2001_size(1)/2,i0005+1) = z0001
  end do
endif
call dfftw_destroy_plan(ftplan3)
write(t0001,"(A)") "fg.dat"
do i0001 = 1, len_trim(t0001)
  if ( t0001( i0001:i0001 ).EQ." " ) t0001( i0001:i0001 ) = "0"
end do
open(f0000, file=trim(t0001))
do i0001=0,z2001_size(1)-1
  do i0002=0,z2001_size(2)-1
    write(f0000,"(I12,A1,I12,A1,E27.17e3,A1,E27.17e3)") i0001,tab,i0002,tab,real(z2001(i0001+1,i0002+1)),tab,aimag(z2001(i0001+1,i0002+1))
  end do
end do
close(f0000)
z2002_size(1) = -1
z2002_size(2) = -1
deallocate(z2002)
z2001_size(1) = -1
z2001_size(2) = -1
deallocate(z2001)
contains
end program test6_2
