!=============================================================================================
! Project name: test6_1
! Project version: 1.0.0
!---------------------------------------------------------------------------------------------
! Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)
! Aqualis version: 188.0.0.0
! Generated date: 2026/08/15 15:44:59
!=============================================================================================
program test6_1
use, intrinsic :: ieee_arithmetic
implicit none
double precision :: d0001
double precision :: d0002
double precision :: d0003
double precision :: d0004
double precision :: d0005
d0001 = -10
!代数微分
d0004 = 1
!数値微分
d0002 = d0001+2+d0005
d0003 = 2.00001d0+d0001+d0005
print *, d0004,(d0003-d0002)/1.0d-5
contains
end program test6_1
