/*=============================================================================================*/
/* Project name: test6_1 */
/* Project version: 1.0.0 */
/*---------------------------------------------------------------------------------------------*/
/* Generated by Aqualis (algorithm and equation analyzer for lightwave simulation) */
/* Aqualis version: 188.0.0.0 */
/* Generated date: 2026/08/15 15:44:59 */
/*=============================================================================================*/
#include <stdio.h>
#include <stdlib.h>
#include <complex.h>
#include <math.h>
#undef I
#define uj _Complex_I
double d0001;
double d0002;
double d0003;
double d0004;
double d0005;
int main()
{
  d0001 = -10;
  /*代数微分*/
  d0004 = 1;
  /*数値微分*/
  d0002 = d0001+2+d0005;
  d0003 = 2.00001E0+d0001+d0005;
  printf("%27.17e%27.17e\n",d0004,(d0003-d0002)/1.0E-5);
  return 0;
}
