/*=============================================================================================*/
/* Project name: test6_1 */
/* Project version: 1.0.0 */
/*---------------------------------------------------------------------------------------------*/
/* Generated by Aqualis (algorithm and equation analyzer for lightwave simulation) */
/* Aqualis version: 188.0.0.0 */
/* Generated date: 2026/09/03 16:30:56 */
/*=============================================================================================*/
#include <stdio.h>
#include <stdlib.h>
#include <complex.h>
#include <math.h>
#undef I
#define uj _Complex_I
int i0001;
double d0001;
double d0002;
double d0003;
double d0004;
double d0005;
double d0006;
double d0007;
double d0008;
double d0009;
double d0010;
double d0011;
double d0012;
double d0013;
double d0014;
double d0015;
double d0016;
double d0017;
double d0018;
double d0019;
double d0020;
double d0021;
double d0022;
double d0023;
double d0024;
double d0025;
double d0026;
double d0027;
double d0028;
int main()
{
  d0001 = -10;
  /*代数微分*/
  d0006 = pow(d0001,2)+1;
  d0007 = sqrt(2*d0006);
  d0008 = sin(d0007-1);
  d0009 = sin(d0007-1);
  d0010 = sqrt(2*d0006);
  d0011 = sin(d0010-1);
  d0012 = sin(d0010-1);
  d0013 = 0;
  for(i0001 = 1; i0001 <= 10; i0001++)
  {
    d0013 = d0013+2*(d0001/(i0001*d0008)-1)*1/(i0001*d0008);
  }
  d0014 = 0;
  for(i0001 = 1; i0001 <= 10; i0001++)
  {
    d0014 = d0014+pow(d0001/(i0001*d0008)-1,2);
  }
  d0015 = 0;
  for(i0001 = 1; i0001 <= 10; i0001++)
  {
    d0015 = d0015;
  }
  d0016 = 0;
  for(i0001 = 1; i0001 <= 10; i0001++)
  {
    d0016 = d0016+pow(d0001/(i0001*d0011)-1,2);
  }
  d0017 = 0;
  for(i0001 = 1; i0001 <= 10; i0001++)
  {
    d0017 = d0017;
  }
  d0018 = 0;
  for(i0001 = 1; i0001 <= 10; i0001++)
  {
    d0018 = d0018+pow(d0001/(i0001*d0012)-1,2);
  }
  d0019 = 0;
  for(i0001 = 1; i0001 <= 10; i0001++)
  {
    d0019 = d0019-2*(d0001/(i0001*d0012)-1)*d0001/pow(i0001*d0012,2)*i0001;
  }
  d0020 = 0;
  for(i0001 = 1; i0001 <= 10; i0001++)
  {
    d0020 = d0020+pow(d0001/(i0001*d0012)-1,2);
  }
  d0004 = 5.0E-1*d0013/sqrt(d0014)+(5.0E-1*d0015/sqrt(d0016)+(5.0E-1*d0017/sqrt(d0018)+5.0E-1*d0019/sqrt(d0020)*cos(d0010-1))*1.0E0/sqrt(2*d0006))*2*d0001;
  /*数値微分*/
  d0021 = pow(d0001,2)+1;
  d0022 = sqrt(2*d0021);
  d0023 = sin(d0022-1);
  d0024 = 0;
  for(i0001 = 1; i0001 <= 10; i0001++)
  {
    d0024 = d0024+pow(d0001/(i0001*d0023)-1,2);
  }
  d0002 = sqrt(d0024);
  d0001 = d0001+1.0E-5;
  d0025 = pow(d0001,2)+1;
  d0026 = sqrt(2*d0025);
  d0027 = sin(d0026-1);
  d0028 = 0;
  for(i0001 = 1; i0001 <= 10; i0001++)
  {
    d0028 = d0028+pow(d0001/(i0001*d0027)-1,2);
  }
  d0003 = sqrt(d0028);
  d0001 = d0001-1.0E-5;
  printf("%27.17e%27.17e\n",d0004,(d0003-d0002)/1.0E-5);
  return 0;
}
