#=============================================================================================
# Project name: test6_1
# Project version: 1.0.0
#---------------------------------------------------------------------------------------------
# Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)
# Aqualis version: 188.0.0.0
# Generated date: 2026/08/15 15:44:59
#=============================================================================================
import numpy
import math
import cmath
import copy
import struct
import re
from scipy.linalg import solve, svd, eig, lu
from scipy.special import jv, yn
import sys
d0001 = 0
d0002 = 0
d0003 = 0
d0004 = 0
d0005 = 0
d0001 = -10
#代数微分
d0004 = 1
#数値微分
d0002 = d0001+2+d0005
d0003 = 2.00001E0+d0001+d0005
print("%27.17e%27.17e" %(d0004,(d0003-d0002)/1.0E-5))
