#=============================================================================================
# Project name: test6_1
# Project version: 1.0.0
#---------------------------------------------------------------------------------------------
# Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)
# Aqualis version: 188.0.0.0
# Generated date: 2026/09/03 16:30:56
#=============================================================================================
import numpy
import math
import cmath
import copy
import struct
import re
from scipy.linalg import solve, svd, eig, lu
from scipy.special import jv, yn
import sys
i0001 = 0
d0001 = 0
d0002 = 0
d0003 = 0
d0004 = 0
d0005 = 0
d0006 = 0
d0007 = 0
d0008 = 0
d0009 = 0
d0010 = 0
d0011 = 0
d0012 = 0
d0013 = 0
d0014 = 0
d0015 = 0
d0016 = 0
d0017 = 0
d0018 = 0
d0019 = 0
d0020 = 0
d0021 = 0
d0022 = 0
d0023 = 0
d0024 = 0
d0025 = 0
d0026 = 0
d0027 = 0
d0028 = 0
d0001 = -10
#代数微分
d0006 = d0001**2+1
d0007 = math.sqrt(2*d0006)
d0008 = math.sin(d0007-1)
d0009 = math.sin(d0007-1)
d0010 = math.sqrt(2*d0006)
d0011 = math.sin(d0010-1)
d0012 = math.sin(d0010-1)
d0013 = 0
for i0001 in range(1, 11, 1):
  d0013 = d0013+2*(d0001/(i0001*d0008)-1)*1/(i0001*d0008)
d0014 = 0
for i0001 in range(1, 11, 1):
  d0014 = d0014+(d0001/(i0001*d0008)-1)**2
d0015 = 0
for i0001 in range(1, 11, 1):
  d0015 = d0015
d0016 = 0
for i0001 in range(1, 11, 1):
  d0016 = d0016+(d0001/(i0001*d0011)-1)**2
d0017 = 0
for i0001 in range(1, 11, 1):
  d0017 = d0017
d0018 = 0
for i0001 in range(1, 11, 1):
  d0018 = d0018+(d0001/(i0001*d0012)-1)**2
d0019 = 0
for i0001 in range(1, 11, 1):
  d0019 = d0019-2*(d0001/(i0001*d0012)-1)*d0001/(i0001*d0012)**2*i0001
d0020 = 0
for i0001 in range(1, 11, 1):
  d0020 = d0020+(d0001/(i0001*d0012)-1)**2
d0004 = 5.0E-1*d0013/math.sqrt(d0014)+(5.0E-1*d0015/math.sqrt(d0016)+(5.0E-1*d0017/math.sqrt(d0018)+5.0E-1*d0019/math.sqrt(d0020)*math.cos(d0010-1))*1.0E0/math.sqrt(2*d0006))*2*d0001
#数値微分
d0021 = d0001**2+1
d0022 = math.sqrt(2*d0021)
d0023 = math.sin(d0022-1)
d0024 = 0
for i0001 in range(1, 11, 1):
  d0024 = d0024+(d0001/(i0001*d0023)-1)**2
d0002 = math.sqrt(d0024)
d0001 = d0001+1.0E-5
d0025 = d0001**2+1
d0026 = math.sqrt(2*d0025)
d0027 = math.sin(d0026-1)
d0028 = 0
for i0001 in range(1, 11, 1):
  d0028 = d0028+(d0001/(i0001*d0027)-1)**2
d0003 = math.sqrt(d0028)
d0001 = d0001-1.0E-5
print("%27.17e%27.17e" %(d0004,(d0003-d0002)/1.0E-5))
