!=============================================================================================
! Project name: test111
! Project version: aaa
!---------------------------------------------------------------------------------------------
! Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)
! Aqualis version: 1.2.1
! Generated date: 2026/07/11 10:38:29
!=============================================================================================
program test111
implicit none
integer :: i0001
double precision :: d0001
double precision,allocatable :: d1001(:)
integer :: d1001_size(1:1) = (/ -1 /)
d1001_size(1) = i0001
allocate(d1001(1:d1001_size(1)))
if(d0001 < 1.25d-1) then
  d1001(1) = 0.0d0
else
  d1001(1) = 7.385753d0*(d0001-1.25d-1)*(d0001-1.25d-1)
endif
d1001_size(1) = -1
deallocate(d1001)
contains
end program test111
