!=============================================================================================
! Project name: test11
! Project version: 1.0.0
!---------------------------------------------------------------------------------------------
! Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)
! Aqualis version: 188.0.0.0
! Generated date: 2026/09/03 16:39:33
!=============================================================================================
program test11
use, intrinsic :: ieee_arithmetic
implicit none
complex(kind(0d0)) :: uj=(0d0,1d0)
integer :: i0001
integer :: i0002
double precision :: d0001
double precision :: d0002
double precision :: d0003
double precision :: d0004
double precision,allocatable :: d1001(:)
integer :: d1001_size(1:1) = (/ -1 /)
double precision,allocatable :: d1002(:)
integer :: d1002_size(1:1) = (/ -1 /)
d1001_size(1) = 21
allocate(d1001(1:d1001_size(1)))
d1002_size(1) = 21
allocate(d1002(1:d1002_size(1)))
!test01
do i0001=-10,10
  d0001 = 2.0d-1*i0001-1.0d1
  d0002 = sqrt(d0001*d0001+1.0d0)
  d1002(11+i0001) = sin(d0002)/d0002
end do
!test02
do i0001=-10,10
  d0001 = 2.0d-1*i0001-1.0d1
  d1001(11+i0001) = d1002(11+i0001)*d0001*sin(d0001)*(d0001+1)
end do
!test03
do i0001=-10,10
  d0001 = 2.0d-1*i0001-1.0d1
  d0003 = 0
  do i0002=-10,10
    d0004 = 2.0d-1*i0002-1.0d1
    d0003 = d0003+d1002(11+i0002)*d0004*sin(d0004+d0001)*(2*d0004+1)
  end do
  d1001(11+i0001) = d0003
end do
d1002_size(1) = -1
deallocate(d1002)
d1001_size(1) = -1
deallocate(d1001)
contains
end program test11
