/*=============================================================================================*/
/* Project name: test4 */
/* Project version: aaa */
/*---------------------------------------------------------------------------------------------*/
/* Generated by Aqualis (algorithm and equation analyzer for lightwave simulation) */
/* Aqualis version: 188.0.0.0 */
/* Generated date: 2026/09/03 16:29:40 */
/*=============================================================================================*/
#include <stdio.h>
#include <stdlib.h>
#include <complex.h>
#include <math.h>
#undef I
#define uj _Complex_I
typedef struct _testClass1
{
  double y1;
} testClass1;
testClass1 ss;
int i0001;
double d0001;
double d0002;
int *i1001;
int i1001_size[1] = { -1 };
/*==========================================================================================*/
/* Subroutine name: func1 */
/* arg01 */
/* arg02 */
/* arg03 */
/* arg04 */
/* arg04_size */
/* arg06 */
/*==========================================================================================*/
void func1(double *arg01, double *arg02, int *arg03, int *arg04, int *arg04_size, testClass1 *arg06)
{
  (*arg01) = (*arg02)+(*arg03)+arg04[0]+(*arg06).y1;
  printf("%27.17e\n",(*arg01));
}
int main()
{
  i1001_size[0] = 4;
  i1001 = (int *)malloc(sizeof(int)*i1001_size[0]);
  i0001 = 1;
  d0001 = 2;
  d0002 = 0;
  i1001[0] = 3;
  ss.y1 = 1.0E2;
  func1(&d0002, &d0001, &i0001, i1001, i1001_size, &ss);
  printf("%27.17e\n",d0002);
  i1001_size[0] = -1;
  free(i1001);
  return 0;
}
