!=============================================================================================
! Project name: test4
! Project version: aaa
!---------------------------------------------------------------------------------------------
! Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)
! Aqualis version: 188.0.0.0
! Generated date: 2026/09/03 16:29:40
!=============================================================================================
program test4
use, intrinsic :: ieee_arithmetic
implicit none
type testClass1
  double precision :: y1
end type testClass1
complex(kind(0d0)) :: uj=(0d0,1d0)
type(testClass1) :: ss
integer :: i0001
double precision :: d0001
double precision :: d0002
integer,allocatable :: i1001(:)
integer :: i1001_size(1:1) = (/ -1 /)
i1001_size(1) = 4
allocate(i1001(1:i1001_size(1)))
i0001 = 1
d0001 = 2
d0002 = 0
i1001(1) = 3
ss%y1 = 1.0d2
call func1(d0002, d0001, i0001, i1001, i1001_size, ss)
print *, d0002
i1001_size(1) = -1
deallocate(i1001)
contains
!=============================================================================================
! Subroutine name: func1
!  arg01
!  arg02
!  arg03
!  arg04
!  arg04_size
!  arg06
!=============================================================================================
subroutine func1(arg01, arg02, arg03, arg04, arg04_size, arg06)
  implicit none
  double precision :: arg01
  double precision :: arg02
  integer :: arg03
  integer,allocatable :: arg04(:)
  integer :: arg04_size(:)
  type(testClass1) :: arg06
  arg01 = arg02+arg03+arg04(1)+arg06%y1
  print *, arg01
end subroutine func1
end program test4
