/*=============================================================================================*/
/* Project name: test4 */
/* Project version: aaa */
/*---------------------------------------------------------------------------------------------*/
/* Generated by Aqualis (algorithm and equation analyzer for lightwave simulation) */
/* Aqualis version: aaa */
/* Generated date: 2026/01/04 12:22:24 */
/*=============================================================================================*/
#include <stdio.h>
#include <stdlib.h>
#include <complex.h>
#include <math.h>
#undef I
#define uj _Complex_I
typedef struct _testClass1
{
  double x1;
} testClass1;
testClass1 ss;
int i0001;
double d0001;
double complex z0001;
int *i1001;
int i1001_size[1] = { -1 };
/*==========================================================================================*/
/* Subroutine name: func1 */
/* arg01 */
/* arg02 */
/* arg03 */
/* arg04 */
/* arg04_size */
/* arg06 */
/*==========================================================================================*/
void func1(double complex *arg01, double *arg02, int *arg03, int *arg04, int *arg04_size, testClass1 *arg06)
{
  (*arg01) = (*arg02)+(*arg03)+arg04[0]+(*arg06).x1;
  printf("%27.12e%27.12e\n",creal((*arg01)),cimag((*arg01)));
}
int main()
{
  i1001_size[0] = 4;
  i1001 = (int *)malloc(sizeof(int)*i1001_size[0]);
  i0001 = 1;
  d0001 = 2;
  z0001 = 0;
  i1001[0] = 3;
  ss.x1 = 1.0E2;
  func1(&z0001, &d0001, &i0001, i1001, i1001_size, &ss);
  printf("%27.12e%27.12e\n",creal(z0001),cimag(z0001));
  i1001_size[0] = -1;
  free(i1001);
  return 0;
}
