#=============================================================================================
# Project name: test4
# Project version: aaa
#---------------------------------------------------------------------------------------------
# Generated by Aqualis (algorithm and equation analyzer for lightwave simulation)
# Aqualis version: aaa
# Generated date: 2026/07/23 14:10:38
#=============================================================================================
import numpy
import math
import cmath
import copy
import struct
import re
from scipy.linalg import solve, svd, eig, lu
from scipy.special import jv, yn
import sys
class testClass1:
  y1 = 0
ss = testClass1()
i0001 = 0
d0001 = 0
d0002 = 0
i1001 = numpy.array([])
i1001_size = numpy.array([-1])
#==========================================================================================
# Subroutine name: func1
# arg01
# arg02
# arg03
# arg04
# arg04_size
# arg06
#==========================================================================================
def func1(arg01, arg02, arg03, arg04, arg04_size, arg06):
  arg01 = arg02+arg03+arg04[0]+arg06.y1
  print("%27.17e" %(arg01))
  return arg01, arg02, arg03, arg06
i1001_size[0] = 4
i1001 = numpy.zeros(i1001_size[0], dtype=int)
i0001 = 1
d0001 = 2
d0002 = 0
i1001[0] = 3
ss.y1 = 1.0E2
d0002, d0001, i0001, ss = func1(d0002, d0001, i0001, i1001, i1001_size, ss)
print("%27.17e" %(d0002))
i1001_size[0] = -1
del i1001
